# Generates lib/builtins/__scalar_arith.py - not itself part of the compiler,
# a one-off codegen tool (run manually, output checked into the repo like any
# other source file). Registers checked/wrapped/saturated arithmetic dunders
# for every scalar type via the `Scalar.method = fn` sigil (discovery.py's
# visit_Assign) - the same mechanism __float.py's __str__/__repr__ use, and
# the pattern __int32.py's i32-only proof-of-concept established. See
# lowering.py's _lower_compiler_checked_binop/_CHECKED_BINOP_OPCODES/
# _CHECKED_FLOAT_BINOP_OPCODES for the underlying mechanism, and memory file
# fallible_arithmetic_decorator_and_int_division_fix.md for the design
# rationale. i128/u128 deliberately excluded - not covered by the earlier
# design discussion, left for a follow-up once their overflow-builtin
# support is separately confirmed.

SIGNED_INT_TYPES = [ 'i8', 'i16', 'i32', 'i64', 'isize' ]
UNSIGNED_INT_TYPES = [ 'u8', 'u16', 'u32', 'u64', 'usize' ]
INT_TYPES = SIGNED_INT_TYPES + UNSIGNED_INT_TYPES
FLOAT_TYPES = [ 'f32', 'f64' ]

# (op kind, base dunder name)
ADD_SUB_MUL = [ ( 'add', '__add__' ), ( 'sub', '__sub__' ), ( 'mul', '__mul__' ) ]
DIV_MOD = [ ( 'floordiv', '__floordiv__' ), ( 'mod', '__mod__' ) ]

def mode_dunder( base: str, prefix: str ) -> str:
	return f'__{prefix}_{base.strip( "_" )}__'

out: list[str] = []

def emit( line: str = '' ) -> None:
	out.append( line )

emit( "# GENERATED by gen_scalar_arith.py - do not hand-edit; re-run the" )
emit( "# generator instead. Registers checked/wrapped/saturated arithmetic" )
emit( "# dunders for every scalar type (see that script's own header comment" )
emit( "# for the full rationale and the mechanism this relies on)." )
emit()

# --- integers: add/sub/mul ---------------------------------------------

for t in INT_TYPES:
	for op, dunder in ADD_SUB_MUL:
		wrapped_dunder = mode_dunder( dunder, 'wrapped' )
		saturated_dunder = mode_dunder( dunder, 'saturated' )
		fn_checked = f'{t}{dunder}{t}'
		fn_wrapped = f'{t}{wrapped_dunder}{t}'
		fn_saturated = f'{t}{saturated_dunder}{t}'

		emit( '@fallible_arithmetic' )
		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_checked}( value: {t}, other: {t} ) -> Result[{t},OverflowError]:' )
		emit( f'\treturn compiler.checked_{op}( value, other )' )
		emit()

		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_wrapped}( value: {t}, other: {t} ) -> {t}:' )
		emit( f'\treturn compiler.wrapped_{op}( value, other )' )
		emit()

		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_saturated}( value: {t}, other: {t} ) -> {t}:' )
		emit( f'\treturn compiler.saturated_{op}( value, other )' )
		emit()

		emit( f'{t}.{dunder} = {fn_checked}' )
		emit( f'{t}.{wrapped_dunder} = {fn_wrapped}' )
		emit( f'{t}.{saturated_dunder} = {fn_saturated}' )
		emit()

# --- integers: floordiv/mod (fallible - ZeroDivisionError - in EVERY mode) --

for t in INT_TYPES:
	error_type = 'ZeroDivisionError|OverflowError' if t in SIGNED_INT_TYPES else 'ZeroDivisionError'
	for op, dunder in DIV_MOD:
		wrapped_dunder = mode_dunder( dunder, 'wrapped' )
		saturated_dunder = mode_dunder( dunder, 'saturated' )
		fn_checked = f'{t}{dunder}{t}'
		fn_wrapped = f'{t}{wrapped_dunder}{t}'
		fn_saturated = f'{t}{saturated_dunder}{t}'

		emit( '@fallible_arithmetic' )
		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_checked}( value: {t}, other: {t} ) -> Result[{t},{error_type}]:' )
		emit( f'\treturn compiler.checked_{op}( value, other )' )
		emit()

		# wrapped/saturated never carry OverflowError (INT_MIN/-1 is handled
		# inline, not surfaced as an error - see ir.py's DivWrap/DivSaturate/
		# ModWrap/ModSaturate comments), signed or not
		emit( '@fallible_arithmetic' )
		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_wrapped}( value: {t}, other: {t} ) -> Result[{t},ZeroDivisionError]:' )
		emit( f'\treturn compiler.wrapped_{op}( value, other )' )
		emit()

		emit( '@fallible_arithmetic' )
		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_saturated}( value: {t}, other: {t} ) -> Result[{t},ZeroDivisionError]:' )
		emit( f'\treturn compiler.saturated_{op}( value, other )' )
		emit()

		emit( f'{t}.{dunder} = {fn_checked}' )
		emit( f'{t}.{wrapped_dunder} = {fn_wrapped}' )
		emit( f'{t}.{saturated_dunder} = {fn_saturated}' )
		emit()

# --- floats: add/sub/mul (checked fallible w/ FloatingPointError; wrapped ---
# --- infallible; saturated == wrapped, no separate opcode - see           ---
# --- lowering.py's _CHECKED_FLOAT_BINOP_OPCODES comment)                  ---

for t in FLOAT_TYPES:
	for op, dunder in ADD_SUB_MUL:
		wrapped_dunder = mode_dunder( dunder, 'wrapped' )
		saturated_dunder = mode_dunder( dunder, 'saturated' )
		fn_checked = f'{t}{dunder}{t}'
		fn_wrapped = f'{t}{wrapped_dunder}{t}'
		fn_saturated = f'{t}{saturated_dunder}{t}'

		emit( '@fallible_arithmetic' )
		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_checked}( value: {t}, other: {t} ) -> Result[{t},FloatingPointError]:' )
		emit( f'\treturn compiler.checked_{op}( value, other )' )
		emit()

		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_wrapped}( value: {t}, other: {t} ) -> {t}:' )
		emit( f'\treturn compiler.wrapped_{op}( value, other )' )
		emit()

		# saturate == wrap for float raw arithmetic - no separate opcode,
		# so this delegates straight to the SAME wrapped_* intrinsic rather
		# than a nonexistent compiler.saturated_* one
		emit( '@private' )
		emit( '@inline' )
		emit( f'def {fn_saturated}( value: {t}, other: {t} ) -> {t}:' )
		emit( f'\treturn compiler.wrapped_{op}( value, other )' )
		emit()

		emit( f'{t}.{dunder} = {fn_checked}' )
		emit( f'{t}.{wrapped_dunder} = {fn_wrapped}' )
		emit( f'{t}.{saturated_dunder} = {fn_saturated}' )
		emit()

# --- floats: truediv (`/`) - checked fallible (ZeroDivisionError|          --
# --- FloatingPointError); wrapped/saturated infallible, both == FloatDiv   --

for t in FLOAT_TYPES:
	dunder = '__truediv__'
	wrapped_dunder = mode_dunder( dunder, 'wrapped' )
	saturated_dunder = mode_dunder( dunder, 'saturated' )
	fn_checked = f'{t}{dunder}{t}'
	fn_wrapped = f'{t}{wrapped_dunder}{t}'
	fn_saturated = f'{t}{saturated_dunder}{t}'

	emit( '@fallible_arithmetic' )
	emit( '@private' )
	emit( '@inline' )
	emit( f'def {fn_checked}( value: {t}, other: {t} ) -> Result[{t},ZeroDivisionError|FloatingPointError]:' )
	emit( f'\treturn compiler.checked_truediv( value, other )' )
	emit()

	emit( '@private' )
	emit( '@inline' )
	emit( f'def {fn_wrapped}( value: {t}, other: {t} ) -> {t}:' )
	emit( f'\treturn compiler.wrapped_truediv( value, other )' )
	emit()

	emit( '@private' )
	emit( '@inline' )
	emit( f'def {fn_saturated}( value: {t}, other: {t} ) -> {t}:' )
	emit( f'\treturn compiler.wrapped_truediv( value, other )' )
	emit()

	emit( f'{t}.{dunder} = {fn_checked}' )
	emit( f'{t}.{wrapped_dunder} = {fn_wrapped}' )
	emit( f'{t}.{saturated_dunder} = {fn_saturated}' )
	emit()

from pathlib import Path
Path( 'lib/builtins/__scalar_arith.py' ).write_text( '\n'.join( out ), encoding = 'utf-8' )
print( f'wrote lib/builtins/__scalar_arith.py, {len(out)} lines' )
