# Generates lib/builtins/__scalar_dunders.py - not itself part of the compiler,
# a one-off codegen tool (run manually, output checked into the repo like any
# other source file). Registers checked/wrapped/saturated arithmetic dunders,
# comparisons (==/!=/</<=/>/>=), and __str__/__repr__, for every scalar type
# via the `Scalar.method = fn` sigil (discovery.py's visit_Assign) - the same
# mechanism __float.py's own f32/f64 __str__/__repr__ use.
#
# Unlike the file this replaces, the FUNCTION BODIES below are no longer
# generated per concrete type - there is exactly ONE real generic function
# body per (operator, mode[, signedness-class for floordiv/mod's error
# type]) pair, specialized per concrete scalar type via the `fn[T]`
# generic-specialization syntax (Scalar.method = fn[ConcreteType] - a
# Specialization, monomorphized on first read - see discovery.py's
# visit_Assign and lowering.py's _resolve_scalar_name/_find_dunder_for_arg/
# _find_method, and type_resolver.py's _attr_lookup_callable). Only the
# per-type REGISTRATION lines are still generated (one line each - no body
# text to get subtly wrong per type). Proven via a real compile+run spike
# (i32/i8 both specializing the SAME generic __add__ body, correct
# per-width overflow boundaries, all 4 arithmetic modes, zero real C
# function emitted for either instantiation) before this file was rewritten
# - see memory file scalar_dunder_dispatch_never_matched_bug_fixed.md for a
# real, independent, pre-existing bug this spike surfaced along the way
# (unrelated to genericity itself - already fixed).
#
# See lowering.py's _lower_compiler_checked_binop/_CHECKED_BINOP_OPCODES/
# _CHECKED_FLOAT_BINOP_OPCODES for the underlying mechanism, and memory file
# fallible_arithmetic_decorator_and_int_division_fix.md for the overall
# design rationale. i128/u128 included - MSVC's own 64-bit __metalpy_wideint/
# __metalpy_wideuint fallback (no native 128-bit type - see emitter_c.py's
# own typedefs and linker_c.has_i128) already makes __metalpy_add_overflow/
# etc's existing _Generic dispatch match correctly under every compiler.
#
# One deliberate, minor behavior deviation from the file this replaces:
# float wrapped_*/saturated_* were @private but NOT @inline in the old
# generated file (an inconsistency with every other combination here, which
# all inline cleanly) - made @inline here too, for uniform zero-overhead
# and to avoid needing to separately verify a non-inline generic-function
# compile-unit path (unexercised by the spike above, and unnecessary: these
# bodies are single-expression, trivially inline-eligible, same shape as
# every int variant already proven).

SIGNED_INT_TYPES = [ 'i8', 'i16', 'i32', 'i64', 'i128', 'isize' ]
UNSIGNED_INT_TYPES = [ 'u8', 'u16', 'u32', 'u64', 'u128', 'usize' ]
INT_TYPES = SIGNED_INT_TYPES + UNSIGNED_INT_TYPES
FLOAT_TYPES = [ 'f32', 'f64' ]

out: list[str] = []

def emit( line: str = '' ) -> None:
	out.append( line )

emit( "# GENERATED by gen_scalar_dunders.py - do not hand-edit; re-run the" )
emit( "# generator instead. One real generic function body per (operator," )
emit( "# mode) pair (see that script's own header comment), specialized per" )
emit( "# concrete scalar type via one registration line each below." )
emit()

# ============================================================================
# generic bodies - int add/sub/mul (uniform across every int type, signed or
# not: overflow is a pure bit-width question, not a signedness one)
# ============================================================================

for kind in ( 'add', 'sub', 'mul' ):
	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def i_{kind}_wrapped[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def i_{kind}_saturated[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.saturated_{kind}( value, other )' )
	emit()

# ============================================================================
# generic bodies - int floordiv/mod. checked's error union depends on
# signedness (INT_MIN/-1 is a real, signed-only overflow case) - two
# generic bodies each, one per signedness class. wrapped/saturated never
# carry OverflowError in EITHER signedness (INT_MIN/-1 is handled inline,
# not surfaced as an error - see ir.py's DivWrap/DivSaturate/ModWrap/
# ModSaturate comments) - one generic body each, shared across all int types.
# ============================================================================

for kind in ( 'floordiv', 'mod' ):
	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_checked_signed[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|OverflowError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_checked_unsigned[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_wrapped[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_saturated[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:' )
	emit( f'\treturn compiler.saturated_{kind}( value, other )' )
	emit()

# ============================================================================
# generic bodies - float add/sub/mul. checked fallible (FloatingPointError);
# wrapped infallible (plain IEEE); saturated == wrapped, no separate opcode
# (see lowering.py's _CHECKED_FLOAT_BINOP_OPCODES comment)
# ============================================================================

for kind in ( 'add', 'sub', 'mul' ):
	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def f_{kind}_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def f_{kind}_wrapped[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def f_{kind}_saturated[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

# ============================================================================
# generic bodies - float truediv (`/`). checked fallible (ZeroDivisionError|
# FloatingPointError); wrapped/saturated infallible, both == FloatDiv
# ============================================================================

emit( '@fallible_arithmetic' )
emit( '@inline' )
emit( 'def f_truediv_checked[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|FloatingPointError]:' )
emit( '\treturn compiler.checked_truediv( value, other )' )
emit()

emit( '@inline' )
emit( 'def f_truediv_wrapped[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.wrapped_truediv( value, other )' )
emit()

emit( '@inline' )
emit( 'def f_truediv_saturated[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.wrapped_truediv( value, other )' )
emit()

# ============================================================================
# generic bodies - bitwise &/|/^ (int types only - no float meaning). Single
# variant each: ir.BitAnd/BitOr/BitXor have no Wrap/Check/Saturate forms at
# all (bitwise ops can't overflow), so there's nothing for ambient
# arithmetic mode to disambiguate - always infallible, plain T-returning.
# ============================================================================

for kind, intrinsic in ( ( 'and', 'bitand' ), ( 'or', 'bitor' ), ( 'xor', 'bitxor' ) ):
	emit( '@inline' )
	emit( f'def i_{kind}[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.{intrinsic}( value, other )' )
	emit()

# ============================================================================
# generic bodies - shifts. << (shl) has real Wrap/Check/Saturate variants
# (ir.ShlWrap/ShlCheck/ShlSaturate - shifting bits out the top is a real,
# already-modeled concern), same 3-variant shape as add/sub/mul. >> (rshift)
# has no such concept (this compiler doesn't check shift-amount-exceeds-
# width for either direction), single-variant infallible like the bitwise
# ops above.
# ============================================================================

emit( '@fallible_arithmetic' )
emit( '@inline' )
emit( 'def i_shl_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:' )
emit( '\treturn compiler.checked_shl( value, other )' )
emit()

emit( '@inline' )
emit( 'def i_shl_wrapped[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.wrapped_shl( value, other )' )
emit()

emit( '@inline' )
emit( 'def i_shl_saturated[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.saturated_shl( value, other )' )
emit()

emit( '@inline' )
emit( 'def i_rshift[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.rshift( value, other )' )
emit()

# ============================================================================
# registrations - one line per (type, dunder name), specializing the
# matching generic body above
# ============================================================================

def mode_dunder( base: str, prefix: str ) -> str:
	return f'__{prefix}_{base.strip( "_" )}__'

emit( '# --- int add/sub/mul -----------------------------------------------' )
emit()
for t in INT_TYPES:
	for kind, dunder in ( ( 'add', '__add__' ), ( 'sub', '__sub__' ), ( 'mul', '__mul__' ) ):
		emit( f'{t}.{dunder} = i_{kind}_checked[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = i_{kind}_wrapped[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "saturated" )} = i_{kind}_saturated[{t}]' )
	emit()

emit( '# --- int floordiv/mod -----------------------------------------------' )
emit()
for t in INT_TYPES:
	signedness = 'signed' if t in SIGNED_INT_TYPES else 'unsigned'
	for kind, dunder in ( ( 'floordiv', '__floordiv__' ), ( 'mod', '__mod__' ) ):
		emit( f'{t}.{dunder} = i_{kind}_checked_{signedness}[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = i_{kind}_wrapped[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "saturated" )} = i_{kind}_saturated[{t}]' )
	emit()

emit( '# --- float add/sub/mul ----------------------------------------------' )
emit()
for t in FLOAT_TYPES:
	for kind, dunder in ( ( 'add', '__add__' ), ( 'sub', '__sub__' ), ( 'mul', '__mul__' ) ):
		emit( f'{t}.{dunder} = f_{kind}_checked[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = f_{kind}_wrapped[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "saturated" )} = f_{kind}_saturated[{t}]' )
	emit()

emit( '# --- float truediv ---------------------------------------------------' )
emit()
for t in FLOAT_TYPES:
	dunder = '__truediv__'
	emit( f'{t}.{dunder} = f_truediv_checked[{t}]' )
	emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = f_truediv_wrapped[{t}]' )
	emit( f'{t}.{mode_dunder( dunder, "saturated" )} = f_truediv_saturated[{t}]' )
emit()

emit( '# --- int/bool bitwise (&/|/^) - single variant, no mode qualification -' )
emit()
# bool is scalar (a valid compiler.bitand/bitor/bitxor operand type just like
# any int), and & / | / ^ on bool has real, well-defined boolean-algebra
# meaning (unlike shift, which bool has no sensible meaning for and never
# type-checks in this language to begin with) - genuinely was reaching this
# old fallback tail (unlike every int type, bool had NO dunder registered at
# all here before), a real gap this rollout would otherwise have left behind
for t in ( *INT_TYPES, 'bool' ):
	for kind, dunder in ( ( 'and', '__and__' ), ( 'or', '__or__' ), ( 'xor', '__xor__' ) ):
		emit( f'{t}.{dunder} = i_{kind}[{t}]' )
emit()

emit( '# --- int shifts (<< checked/wrapped/saturated, >> single variant) ---' )
emit()
for t in INT_TYPES:
	emit( f'{t}.__lshift__ = i_shl_checked[{t}]' )
	emit( f'{t}.{mode_dunder( "__lshift__", "wrapped" )} = i_shl_wrapped[{t}]' )
	emit( f'{t}.{mode_dunder( "__lshift__", "saturated" )} = i_shl_saturated[{t}]' )
	emit( f'{t}.__rshift__ = i_rshift[{t}]' )
emit()

# ============================================================================
# comparisons (==, !=, <, <=, >, >=) - single variant each, no Wrap/Check/
# Saturate mode to disambiguate (comparison never overflows, same "always
# infallible, plain bool-returning" shape as the bitwise ops above). One
# generic body per op, shared by every int type, float type, AND bool alike
# (unlike floordiv/mod, comparison has no signedness- or kind-dependent
# split) - backed by compiler.cmp_eq/cmp_ne/cmp_lt/cmp_le/cmp_gt/cmp_ge
# (lowering.py's _lower_compiler_cmp), the same fixed-opcode-intrinsic
# pattern compiler.bitand/etc already use for the bitwise ops. Registering
# these lets ordinary comparison dispatch (lowering.py's _expr_Compare/
# _lower_eq_or_ne/_lower_operand_compare/_classify_leaf_pair_eq) find a real
# dunder for a Scalar operand too, eliminating the isinstance(Scalar)
# special-casing those methods used to gate dunder lookup on entirely -
# _find_dunder_for_arg already treats a Scalar-registered dunder identically
# to a real class's own method (both just read .names), so a Scalar with
# nothing registered under a given name still just misses cleanly and falls
# through to the pre-existing flat-Cmp fallback, exactly like a class that
# never defined the dunder at all - same precedent as arithmetic's own
# binop_fallback_eliminated rollout. NoneType (also Scalar) deliberately
# gets none of these - it never reaches ordinary dunder lookup at all (see
# _lower_eq_or_ne's own docstring on `None == x`), so registering comparison
# dunders for it would be dead code, never actually looked up.
# ============================================================================

for kind, intrinsic in ( ( 'eq', 'cmp_eq' ), ( 'ne', 'cmp_ne' ), ( 'lt', 'cmp_lt' ), ( 'le', 'cmp_le' ), ( 'gt', 'cmp_gt' ), ( 'ge', 'cmp_ge' ) ):
	emit( '@inline' )
	emit( f'def scalar_{kind}[T]( value: T, other: T ) -> bool:' )
	emit( f'\treturn compiler.{intrinsic}( value, other )' )
	emit()

emit( '# --- comparisons (==, !=, <, <=, >, >=) -------------------------------' )
emit()
for t in ( *INT_TYPES, *FLOAT_TYPES, 'bool' ):
	for kind, dunder in ( ( 'eq', '__eq__' ), ( 'ne', '__ne__' ), ( 'lt', '__lt__' ), ( 'le', '__le__' ), ( 'gt', '__gt__' ), ( 'ge', '__ge__' ) ):
		emit( f'{t}.{dunder} = scalar_{kind}[{t}]' )
	emit()

# ============================================================================
# .to_T() - value-preserving numeric conversion, int<->int only this pass
# (float conversions deferred - see SYNTAX.md). Genuinely separate from
# T(x) (above): succeeds iff the source's VALUE fits target's [MIN,MAX],
# independent of bit width - can fail even same-width (i8(-1).to_u8() must
# fail; u8(i8(-1)) via T(x) never does). Exactly one check, no wrapped/
# saturated variant - see compiler.checked_convert's own comment for why.
# Self-conversion (T.to_T()) is generated separately below as a trivial,
# always-infallible identity - provably always in-range, so it's plain
# T-returning (no Result, not @fallible_arithmetic), matching the same
# "genuinely infallible => don't wrap in Result" precedent
# wrapped_add/saturated_add already established above.
# ============================================================================

emit( '@fallible_arithmetic' )
emit( '@inline' )
emit( 'def i_to_i[S,T]( value: S ) -> Result[T,OverflowError]:' )
emit( '\treturn compiler.checked_convert( T, value )' )
emit()

emit( '@inline' )
emit( 'def i_to_i_identity[T]( value: T ) -> T:' )
emit( '\treturn value' )
emit()

emit( '# --- int-to-int value-preserving conversions ------------------------' )
emit()
for source in INT_TYPES:
	for target in INT_TYPES:
		if source == target:
			emit( f'{source}.to_{target} = i_to_i_identity[{source}]' )
		else:
			emit( f'{source}.to_{target} = i_to_i[{source},{target}]' )
	emit()

# ============================================================================
# __str__/__repr__ - decimal text, PLAN_STR_FORMAT.md item 6 (bare f"{x}"/
# str(x) for a fixed-width int scalar - previously deliberately unsupported,
# see lowering.py's own comment at the f-string !s/!r dispatch site: "a
# scalar (i32, bool, ...) has no __str__ of its own, only the boxed classes
# do"). One generic body per signedness - unsigned needs no sign handling;
# signed needs real care around the MIN value (int8.MIN's magnitude doesn't
# fit in int8, same class of problem int.__init__ works around by widening -
# no wider type exists past i128/u128 here, so this sidesteps it differently
# instead: extract digits via C-truncating %/// directly on the untouched,
# possibly-negative value (this compiler's own runtime `%`/`//` truncate
# toward zero for negative operands, confirmed by emitter_c.py's
# _emit_int_division - matching plain C, not Python's floor semantics), then
# negate each single-digit remainder (always in [-9,0], trivially safe to
# negate for ANY width, unlike the full value) rather than ever negating the
# full-width value itself. repr() == str() for every int type (matching
# int.__repr__/f64.__repr__'s own precedent) - both registered to the SAME
# specialization below, not a separate delegating body.
# ============================================================================

emit( "_INT_DECIMAL_DIGIT_CHARS: str = '0123456789'" )
emit()

emit( 'def i_str_unsigned[T]( value: T ) -> str:' )
emit( "\tif value == 0:" )
emit( "\t\treturn '0'" )
emit( '\tdigits: list[str] = list[str]() # least-significant digit first' )
emit( "\twith compiler.panic_arithmetic( 'dividing/moduloing a non-negative value by the literal 10 never zero-divides or overflows' ):" )
emit( '\t\tv: T = value' )
emit( '\t\twhile v != 0:' )
emit( '\t\t\tdigit: T = v % 10' )
emit( '\t\t\tdigit_index: usize = usize( digit )' )
emit( '\t\t\tdigit_index_end: usize = digit_index + 1' )
emit( "\t\t\tdigits.append( _INT_DECIMAL_DIGIT_CHARS._byte_slice( digit_index, digit_index_end )).unwrap( 'i_str_unsigned: append failed' )" )
emit( '\t\t\tv = v // 10' )
emit( '\tcount: usize = digits.__len__()' )
emit( '\tordered: list[str] = list[str]() # most-significant digit first' )
emit( '\ti: usize = count' )
emit( "\twith compiler.panic_arithmetic( 'bounded by count, cannot underflow' ):" )
emit( '\t\twhile i > 0:' )
emit( '\t\t\ti -= 1' )
emit( "\t\t\tordered.append( digits.__getitem__( i ).unwrap( 'i_str_unsigned: index in bounds by construction' )).unwrap( 'i_str_unsigned: append failed' )" )
emit( "\treturn ''.join( ordered )" )
emit()

emit( 'def i_str_signed[T]( value: T ) -> str:' )
emit( "\tif value == 0:" )
emit( "\t\treturn '0'" )
emit( '\tis_negative: bool = value < 0' )
emit( '\tdigits: list[str] = list[str]() # least-significant digit first' )
emit( "\twith compiler.panic_arithmetic( 'dividing/moduloing by the literal 10 never zero-divides; the divisor is never -1, so the signed MIN/-1 overflow case never applies here' ):" )
emit( '\t\tv: T = value' )
emit( '\t\twhile v != 0:' )
emit( '\t\t\tdigit: T = v % 10 # C-truncating: same sign as v (or zero), never MIN-magnitude' )
emit( '\t\t\tmagnitude_digit: T = -digit if digit < 0 else digit # a single digit (0-9) - safe to negate for any width, unlike v itself' )
emit( '\t\t\tdigit_index: usize = usize( magnitude_digit )' )
emit( '\t\t\tdigit_index_end: usize = digit_index + 1' )
emit( "\t\t\tdigits.append( _INT_DECIMAL_DIGIT_CHARS._byte_slice( digit_index, digit_index_end )).unwrap( 'i_str_signed: append failed' )" )
emit( '\t\t\tv = v // 10' )
emit( '\tcount: usize = digits.__len__()' )
emit( '\tordered: list[str] = list[str]() # most-significant digit first' )
emit( '\ti: usize = count' )
emit( "\twith compiler.panic_arithmetic( 'bounded by count, cannot underflow' ):" )
emit( '\t\twhile i > 0:' )
emit( '\t\t\ti -= 1' )
emit( "\t\t\tordered.append( digits.__getitem__( i ).unwrap( 'i_str_signed: index in bounds by construction' )).unwrap( 'i_str_signed: append failed' )" )
emit( "\tjoined: str = ''.join( ordered )" )
emit( "\tif is_negative:" )
emit( "\t\treturn '-' + joined" )
emit( '\treturn joined' )
emit()

emit( '# --- __str__/__repr__ -------------------------------------------------' )
emit()
for t in SIGNED_INT_TYPES:
	emit( f'{t}.__str__ = i_str_signed[{t}]' )
	emit( f'{t}.__repr__ = i_str_signed[{t}]' )
emit()
for t in UNSIGNED_INT_TYPES:
	emit( f'{t}.__str__ = i_str_unsigned[{t}]' )
	emit( f'{t}.__repr__ = i_str_unsigned[{t}]' )
emit()

from pathlib import Path
Path( 'lib/builtins/__scalar_dunders.py' ).write_text( '\n'.join( out ), encoding = 'utf-8' )
print( f'wrote lib/builtins/__scalar_dunders.py, {len(out)} lines' )
