# Generates lib/builtins/__scalar_arith.py - not itself part of the compiler,
# a one-off codegen tool (run manually, output checked into the repo like any
# other source file). Registers checked/wrapped/saturated arithmetic dunders
# for every scalar type via the `Scalar.method = fn` sigil (discovery.py's
# visit_Assign) - the same mechanism __float.py's __str__/__repr__ use.
#
# Unlike the file this replaces, the FUNCTION BODIES below are no longer
# generated per concrete type - there is exactly ONE real generic function
# body per (operator, mode[, signedness-class for floordiv/mod's error
# type]) pair, specialized per concrete scalar type via the `fn[T]`
# generic-specialization syntax (Scalar.method = fn[ConcreteType] - a
# Specialization, monomorphized on first read - see discovery.py's
# visit_Assign and lowering.py's _resolve_scalar_name/_find_dunder_for_arg/
# _find_method, and type_resolver.py's _attr_lookup_callable). Only the
# per-type REGISTRATION lines are still generated (one line each - no body
# text to get subtly wrong per type). Proven via a real compile+run spike
# (i32/i8 both specializing the SAME generic __add__ body, correct
# per-width overflow boundaries, all 4 arithmetic modes, zero real C
# function emitted for either instantiation) before this file was rewritten
# - see memory file scalar_dunder_dispatch_never_matched_bug_fixed.md for a
# real, independent, pre-existing bug this spike surfaced along the way
# (unrelated to genericity itself - already fixed).
#
# See lowering.py's _lower_compiler_checked_binop/_CHECKED_BINOP_OPCODES/
# _CHECKED_FLOAT_BINOP_OPCODES for the underlying mechanism, and memory file
# fallible_arithmetic_decorator_and_int_division_fix.md for the overall
# design rationale. i128/u128 included - MSVC's own 64-bit __metalpy_wideint/
# __metalpy_wideuint fallback (no native 128-bit type - see emitter_c.py's
# own typedefs and linker_c.has_i128) already makes __metalpy_add_overflow/
# etc's existing _Generic dispatch match correctly under every compiler.
#
# One deliberate, minor behavior deviation from the file this replaces:
# float wrapped_*/saturated_* were @private but NOT @inline in the old
# generated file (an inconsistency with every other combination here, which
# all inline cleanly) - made @inline here too, for uniform zero-overhead
# and to avoid needing to separately verify a non-inline generic-function
# compile-unit path (unexercised by the spike above, and unnecessary: these
# bodies are single-expression, trivially inline-eligible, same shape as
# every int variant already proven).

SIGNED_INT_TYPES = [ 'i8', 'i16', 'i32', 'i64', 'i128', 'isize' ]
UNSIGNED_INT_TYPES = [ 'u8', 'u16', 'u32', 'u64', 'u128', 'usize' ]
INT_TYPES = SIGNED_INT_TYPES + UNSIGNED_INT_TYPES
FLOAT_TYPES = [ 'f32', 'f64' ]

out: list[str] = []

def emit( line: str = '' ) -> None:
	out.append( line )

emit( "# GENERATED by gen_scalar_arith.py - do not hand-edit; re-run the" )
emit( "# generator instead. One real generic function body per (operator," )
emit( "# mode) pair (see that script's own header comment), specialized per" )
emit( "# concrete scalar type via one registration line each below." )
emit()

# ============================================================================
# generic bodies - int add/sub/mul (uniform across every int type, signed or
# not: overflow is a pure bit-width question, not a signedness one)
# ============================================================================

for kind in ( 'add', 'sub', 'mul' ):
	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def i_{kind}_wrapped[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def i_{kind}_saturated[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.saturated_{kind}( value, other )' )
	emit()

# ============================================================================
# generic bodies - int floordiv/mod. checked's error union depends on
# signedness (INT_MIN/-1 is a real, signed-only overflow case) - two
# generic bodies each, one per signedness class. wrapped/saturated never
# carry OverflowError in EITHER signedness (INT_MIN/-1 is handled inline,
# not surfaced as an error - see ir.py's DivWrap/DivSaturate/ModWrap/
# ModSaturate comments) - one generic body each, shared across all int types.
# ============================================================================

for kind in ( 'floordiv', 'mod' ):
	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_checked_signed[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|OverflowError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_checked_unsigned[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_wrapped[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def i_{kind}_saturated[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:' )
	emit( f'\treturn compiler.saturated_{kind}( value, other )' )
	emit()

# ============================================================================
# generic bodies - float add/sub/mul. checked fallible (FloatingPointError);
# wrapped infallible (plain IEEE); saturated == wrapped, no separate opcode
# (see lowering.py's _CHECKED_FLOAT_BINOP_OPCODES comment)
# ============================================================================

for kind in ( 'add', 'sub', 'mul' ):
	emit( '@fallible_arithmetic' )
	emit( '@inline' )
	emit( f'def f_{kind}_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:' )
	emit( f'\treturn compiler.checked_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def f_{kind}_wrapped[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

	emit( '@inline' )
	emit( f'def f_{kind}_saturated[T]( value: T, other: T ) -> T:' )
	emit( f'\treturn compiler.wrapped_{kind}( value, other )' )
	emit()

# ============================================================================
# generic bodies - float truediv (`/`). checked fallible (ZeroDivisionError|
# FloatingPointError); wrapped/saturated infallible, both == FloatDiv
# ============================================================================

emit( '@fallible_arithmetic' )
emit( '@inline' )
emit( 'def f_truediv_checked[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|FloatingPointError]:' )
emit( '\treturn compiler.checked_truediv( value, other )' )
emit()

emit( '@inline' )
emit( 'def f_truediv_wrapped[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.wrapped_truediv( value, other )' )
emit()

emit( '@inline' )
emit( 'def f_truediv_saturated[T]( value: T, other: T ) -> T:' )
emit( '\treturn compiler.wrapped_truediv( value, other )' )
emit()

# ============================================================================
# registrations - one line per (type, dunder name), specializing the
# matching generic body above
# ============================================================================

def mode_dunder( base: str, prefix: str ) -> str:
	return f'__{prefix}_{base.strip( "_" )}__'

emit( '# --- int add/sub/mul -----------------------------------------------' )
emit()
for t in INT_TYPES:
	for kind, dunder in ( ( 'add', '__add__' ), ( 'sub', '__sub__' ), ( 'mul', '__mul__' ) ):
		emit( f'{t}.{dunder} = i_{kind}_checked[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = i_{kind}_wrapped[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "saturated" )} = i_{kind}_saturated[{t}]' )
	emit()

emit( '# --- int floordiv/mod -----------------------------------------------' )
emit()
for t in INT_TYPES:
	signedness = 'signed' if t in SIGNED_INT_TYPES else 'unsigned'
	for kind, dunder in ( ( 'floordiv', '__floordiv__' ), ( 'mod', '__mod__' ) ):
		emit( f'{t}.{dunder} = i_{kind}_checked_{signedness}[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = i_{kind}_wrapped[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "saturated" )} = i_{kind}_saturated[{t}]' )
	emit()

emit( '# --- float add/sub/mul ----------------------------------------------' )
emit()
for t in FLOAT_TYPES:
	for kind, dunder in ( ( 'add', '__add__' ), ( 'sub', '__sub__' ), ( 'mul', '__mul__' ) ):
		emit( f'{t}.{dunder} = f_{kind}_checked[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = f_{kind}_wrapped[{t}]' )
		emit( f'{t}.{mode_dunder( dunder, "saturated" )} = f_{kind}_saturated[{t}]' )
	emit()

emit( '# --- float truediv ---------------------------------------------------' )
emit()
for t in FLOAT_TYPES:
	dunder = '__truediv__'
	emit( f'{t}.{dunder} = f_truediv_checked[{t}]' )
	emit( f'{t}.{mode_dunder( dunder, "wrapped" )} = f_truediv_wrapped[{t}]' )
	emit( f'{t}.{mode_dunder( dunder, "saturated" )} = f_truediv_saturated[{t}]' )
emit()

from pathlib import Path
Path( 'lib/builtins/__scalar_arith.py' ).write_text( '\n'.join( out ), encoding = 'utf-8' )
print( f'wrote lib/builtins/__scalar_arith.py, {len(out)} lines' )
