# Real-compile-and-run behavioral test for fixed-width int scalar __str__/
# __repr__ (lib/builtins/__scalar_dunders.py's i_str_signed[T]/
# i_str_unsigned[T], generated by gen_scalar_dunders.py). Closes
# PLAN_STR_FORMAT.md item 6 for the int side: i8/u8/i16/u16/i32/u32/i64/u64/
# i128/u128/isize/usize previously had no __str__ of their own at all (see
# lowering.py's f-string !s/!r dispatch, and the "a scalar (i32, bool, ...)
# has no __str__ of its own" comment that used to sit there) - a bare
# `x: i8 = 0; print(f'{x}')` failed to compile with "f-string requires
# i8.__str__() to be available". f32/f64 already had their own real __str__/
# __repr__ (lib/builtins/__float.py) via the same `Scalar.method = fn` sigil
# mechanism this reuses.
#
# The signed digit-extraction algorithm deliberately never negates the
# full-width value (int8.MIN's magnitude doesn't fit in int8, the same class
# of problem int.__init__ works around by widening to i64 - no wider type
# exists past i128/u128 here). Instead it extracts digits via C-truncating
# %/// directly on the untouched, possibly-negative value (this compiler's
# runtime `%`/`//` truncate toward zero for negative operands, matching C,
# not Python's floor semantics - confirmed by emitter_c.py's
# _emit_int_division) and only ever negates a single-digit remainder
# (always in [-9,0], trivially safe for any width). MIN/MAX-value coverage
# below is the real point of this test - a naive "negate then extract
# digits" implementation crashes or corrupts exactly there.
#
# A real, independent, pre-existing compiler bug was found and fixed while
# building this: constructing an i64::MIN or i128::MIN literal (e.g.
# `e: i64 = -9223372036854775808`) compiled cleanly but crashed at runtime
# (SIGILL) - emitter_c.py's _emit_wide_int_const cast an out-of-range
# unsigned magnitude to the target signed type (already producing the
# correct negative MIN value via the same two's-complement bit-reinterpret
# this codebase already relies on elsewhere) and then negated THAT a second
# time, overflowing the signed type again - real signed-overflow UB, not
# just for i128 but for i64 (and isize on this platform) too. Fixed by
# negating in the same-width UNSIGNED type first (well-defined modular
# wraparound) and casting to the signed type last. wide_int_test.py/
# emitter_c_test.py/etc's existing i128 literal coverage happened to never
# hit the exact MIN magnitude.
#
# i128/u128 MIN/MAX coverage is split into its own _HAS_I128-gated test,
# same convention wide_int_test.py already uses: MSVC's own i128/u128 is a
# 64-bit fallback (no native 128-bit type, see emitter_c.py's
# __metalpy_wideint typedef comment), so a genuine 128-bit boundary value
# doesn't survive round-trip under cl.exe - that's a known, pre-existing
# platform limitation, not a bug in this feature.

import unittest

import emitter_c
import linker_c
import test_support
from test_support import RealCompileMixin

_CC = linker_c.detect_cc()
_HAS_I128 = linker_c.has_i128( _CC )

_64BIT_SIGNED_MIN = [
	( 'i8', '-128' ),
	( 'i16', '-32768' ),
	( 'i32', '-2147483648' ),
	( 'i64', '-9223372036854775808' ),
]

_64BIT_UNSIGNED_MAX = [
	( 'u8', '255' ),
	( 'u16', '65535' ),
	( 'u32', '4294967295' ),
	( 'u64', '18446744073709551615' ),
]

_128BIT_SIGNED_MIN = [ ( 'i128', '-170141183460469231731687303715884105728' ) ]
_128BIT_UNSIGNED_MAX = [ ( 'u128', '340282366920938463463374607431768211455' ) ]

def _build_matrix_source( type_pairs: list[tuple[str,str]], extra_lines: list[str] = [] ) -> str:
	# `check` is a plain incrementing counter, never at risk of real
	# overflow (a few dozen at most) - wrap_arithmetic sidesteps the default
	# checked-mode Result ceremony that would otherwise force every
	# `check += 1` to propagate through main()'s own `-> i32` return type
	lines = [ 'def main() -> i32:', '\twith compiler.wrap_arithmetic:', '\t\tcheck: i32 = 0' ]
	for stem, expected in type_pairs:
		lines.append( '\t\tcheck += 1' )
		lines.append( f"\t\tv_{stem}: {stem} = {expected}" )
		lines.append( f"\t\tif v_{stem}.__str__() != '{expected}':" )
		lines.append( '\t\t\treturn check' )
		lines.append( '\t\tcheck += 1' )
		lines.append( f"\t\tif v_{stem}.__repr__() != '{expected}':" )
		lines.append( '\t\t\treturn check' )
	for extra in extra_lines:
		lines.append( '\t\tcheck += 1' )
		lines.append( '\t\t' + extra.replace( '\n', '\n\t\t' ) )
	lines.append( '\t\treturn 0' )
	return '\n'.join( lines )

def _matrix_check_names( type_pairs: list[tuple[str,str]], extra_names: list[str] = [] ) -> list[str]:
	# kept in lockstep with _build_matrix_source's own emission order by
	# construction, rather than hand-duplicated
	names = []
	for stem, expected in type_pairs:
		names.append( f'{stem}.__str__() == {expected!r}' )
		names.append( f'{stem}.__repr__() == {expected!r}' )
	names += extra_names
	return names

# zero and an ordinary small value, both signednesses - the MIN/MAX sweep
# never exercises the `value == 0` early-return or an ordinary multi-digit-
# but-not-boundary value
_ZERO_AND_ORDINARY_EXTRAS = [
	( "z: i32 = 0\nif z.__str__() != '0':\n\treturn check", "i32(0).__str__() == '0'" ),
	( "zu: u32 = 0\nif zu.__str__() != '0':\n\treturn check", "u32(0).__str__() == '0'" ),
	( "p: i16 = 12345\nif p.__str__() != '12345':\n\treturn check", "i16(12345).__str__() == '12345'" ),
	( "n: i16 = -12345\nif n.__str__() != '-12345':\n\treturn check", "i16(-12345).__str__() == '-12345'" ),
]

_64BIT_TYPE_PAIRS = _64BIT_SIGNED_MIN + _64BIT_UNSIGNED_MAX
_64BIT_MATRIX_SOURCE = _build_matrix_source( _64BIT_TYPE_PAIRS, [ src for src, _ in _ZERO_AND_ORDINARY_EXTRAS ] )
_64BIT_MATRIX_CHECK_NAMES = _matrix_check_names( _64BIT_TYPE_PAIRS, [ name for _, name in _ZERO_AND_ORDINARY_EXTRAS ] )

_128BIT_TYPE_PAIRS = _128BIT_SIGNED_MIN + _128BIT_UNSIGNED_MAX
_128BIT_MATRIX_SOURCE = _build_matrix_source( _128BIT_TYPE_PAIRS )
_128BIT_MATRIX_CHECK_NAMES = _matrix_check_names( _128BIT_TYPE_PAIRS )


@unittest.skipUnless( test_support.HAS_CC, 'no C compiler (clang/gcc/msvc) found - skipping real-compile scalar-str tests' )
class ScalarStrBehaviorTests( RealCompileMixin, unittest.TestCase ):
	def _assert_program_succeeds( self, code: str, check_names: list[str] ) -> None:
		compiler = self._compile_source( code )
		result = self._build_and_run( compiler, emitter_c.emit_c( compiler ), None )
		if result.returncode == 0:
			return
		if 1 <= result.returncode <= len( check_names ):
			failed = check_names[ result.returncode - 1 ]
		else:
			failed = f'(unmapped exit code {result.returncode} - possible crash/corruption, not a plain check failure)'
		self.fail(
			f'program exited {result.returncode}, expected 0. Failed check: {failed}\n'
			f'stdout: {result.stdout}\nstderr: {result.stderr}'
		)

	def test_str_and_repr_matrix_64bit_and_narrower_types( self ) -> None:
		self._assert_program_succeeds( _64BIT_MATRIX_SOURCE, _64BIT_MATRIX_CHECK_NAMES )

	@unittest.skipUnless( _HAS_I128, "MSVC's i128/u128 64-bit fallback doesn't have true 128-bit range - see emitter_c.py's __metalpy_wideint" )
	def test_str_and_repr_matrix_i128_u128( self ) -> None:
		self._assert_program_succeeds( _128BIT_MATRIX_SOURCE, _128BIT_MATRIX_CHECK_NAMES )

	def test_bare_fstring_interpolation( self ) -> None:
		# the original motivating case: `x: i8 = 0; print(f'{x}')` - bare
		# f-string interpolation with no format spec dispatches to __str__
		# via ordinary method lookup (lowering.py's _lower_fstring_part),
		# same path str(x)/print() already use for any other type
		self._assert_program_succeeds( '''
def main() -> i32:
	a: i8 = -128
	if f'{a}' != '-128':
		return 1
	b: u64 = 18446744073709551615
	if f'{b}' != '18446744073709551615':
		return 2
	return 0
''', [ "f'{i8(-128)}' == '-128'", "f'{u64::MAX}' == '18446744073709551615'" ] )

	def test_str_builtin_call( self ) -> None:
		# str(x) (lib/builtins/__init__.py's str.__call__[T]) generically
		# calls x.__str__() for any T - proves this reaches the new
		# fixed-width int dunders too, not just the f-string-specific path
		self._assert_program_succeeds( '''
def main() -> i32:
	x: i64 = -9223372036854775808
	s: str = str( x )
	if s != '-9223372036854775808':
		return 1
	return 0
''', [ 'str(i64::MIN) == "-9223372036854775808"' ] )

	def test_i64_min_literal_does_not_crash( self ) -> None:
		# regression coverage for the literal-emission bug this feature work
		# uncovered (see this file's own header comment) - constructing and
		# comparing an i64::MIN literal must not SIGILL. Deliberately
		# exercises the literal alone (no __str__ involved) so a future
		# regression here is diagnosed as the literal bug specifically, not
		# confused with a digit-extraction bug.
		self._assert_program_succeeds( '''
def main() -> i32:
	b: i64 = -9223372036854775808
	if not ( b < 0 ):
		return 1
	d: i64 = -5
	if d != -5:
		return 2
	return 0
''', [ 'i64::MIN < 0', 'ordinary negative i64 literal unaffected' ] )

	@unittest.skipUnless( _HAS_I128, "MSVC's i128/u128 64-bit fallback doesn't have true 128-bit range - see emitter_c.py's __metalpy_wideint" )
	def test_i128_min_literal_does_not_crash( self ) -> None:
		self._assert_program_succeeds( '''
def main() -> i32:
	a: i128 = -170141183460469231731687303715884105728
	if not ( a < 0 ):
		return 1
	c: i128 = -5
	if c != -5:
		return 2
	return 0
''', [ 'i128::MIN < 0', 'ordinary negative i128 literal unaffected' ] )


# PLAN_STR_FORMAT.md item 6, bool half: bool.__str__/__repr__
# (lib/builtins/__scalar_dunders.py's bool_str, registered via the same
# `Scalar.method = fn` sigil as the int/float dunders above) - matches
# Python's own str(True)/str(False) capitalization exactly ('True'/'False'),
# not lowercase - no pre-existing metalpy convention for boolean text output
# existed to defer to instead.
@unittest.skipUnless( test_support.HAS_CC, 'no C compiler (clang/gcc/msvc) found - skipping real-compile scalar-str tests' )
class BoolStrBehaviorTests( RealCompileMixin, unittest.TestCase ):
	def _assert_program_succeeds( self, code: str, check_names: list[str] ) -> None:
		compiler = self._compile_source( code )
		result = self._build_and_run( compiler, emitter_c.emit_c( compiler ), None )
		if result.returncode == 0:
			return
		if 1 <= result.returncode <= len( check_names ):
			failed = check_names[ result.returncode - 1 ]
		else:
			failed = f'(unmapped exit code {result.returncode} - possible crash/corruption, not a plain check failure)'
		self.fail(
			f'program exited {result.returncode}, expected 0. Failed check: {failed}\n'
			f'stdout: {result.stdout}\nstderr: {result.stderr}'
		)

	def test_str_and_repr( self ) -> None:
		self._assert_program_succeeds( '''
def main() -> i32:
	t: bool = True
	if t.__str__() != 'True':
		return 1
	if t.__repr__() != 'True':
		return 2
	f: bool = False
	if f.__str__() != 'False':
		return 3
	if f.__repr__() != 'False':
		return 4
	return 0
''', [
			"True.__str__() == 'True'", "True.__repr__() == 'True'",
			"False.__str__() == 'False'", "False.__repr__() == 'False'",
		] )

	def test_bare_fstring_interpolation( self ) -> None:
		# the motivating case: bare f"{some_bool}" - no auto-boxing, ordinary
		# method dispatch same as every other scalar (scalar_str_test.py's
		# own int coverage above)
		self._assert_program_succeeds( '''
def main() -> i32:
	t: bool = True
	if f'{t}' != 'True':
		return 1
	f: bool = False
	if f'{f}' != 'False':
		return 2
	return 0
''', [ "f'{True}' == 'True'", "f'{False}' == 'False'" ] )

	def test_str_builtin_call( self ) -> None:
		self._assert_program_succeeds( '''
def main() -> i32:
	t: bool = True
	s: str = str( t )
	if s != 'True':
		return 1
	return 0
''', [ 'str(True) == "True"' ] )


if __name__ == '__main__':
	unittest.main()
