# GENERATED by gen_scalar_arith.py - do not hand-edit; re-run the
# generator instead. Registers checked/wrapped/saturated arithmetic
# dunders for every scalar type (see that script's own header comment
# for the full rationale and the mechanism this relies on).

@fallible_arithmetic
@private
@inline
def i8__add__i8( value: i8, other: i8 ) -> Result[i8,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def i8__wrapped_add__i8( value: i8, other: i8 ) -> i8:
	return compiler.wrapped_add( value, other )

@private
@inline
def i8__saturated_add__i8( value: i8, other: i8 ) -> i8:
	return compiler.saturated_add( value, other )

i8.__add__ = i8__add__i8
i8.__wrapped_add__ = i8__wrapped_add__i8
i8.__saturated_add__ = i8__saturated_add__i8

@fallible_arithmetic
@private
@inline
def i8__sub__i8( value: i8, other: i8 ) -> Result[i8,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def i8__wrapped_sub__i8( value: i8, other: i8 ) -> i8:
	return compiler.wrapped_sub( value, other )

@private
@inline
def i8__saturated_sub__i8( value: i8, other: i8 ) -> i8:
	return compiler.saturated_sub( value, other )

i8.__sub__ = i8__sub__i8
i8.__wrapped_sub__ = i8__wrapped_sub__i8
i8.__saturated_sub__ = i8__saturated_sub__i8

@fallible_arithmetic
@private
@inline
def i8__mul__i8( value: i8, other: i8 ) -> Result[i8,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def i8__wrapped_mul__i8( value: i8, other: i8 ) -> i8:
	return compiler.wrapped_mul( value, other )

@private
@inline
def i8__saturated_mul__i8( value: i8, other: i8 ) -> i8:
	return compiler.saturated_mul( value, other )

i8.__mul__ = i8__mul__i8
i8.__wrapped_mul__ = i8__wrapped_mul__i8
i8.__saturated_mul__ = i8__saturated_mul__i8

@fallible_arithmetic
@private
@inline
def i16__add__i16( value: i16, other: i16 ) -> Result[i16,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def i16__wrapped_add__i16( value: i16, other: i16 ) -> i16:
	return compiler.wrapped_add( value, other )

@private
@inline
def i16__saturated_add__i16( value: i16, other: i16 ) -> i16:
	return compiler.saturated_add( value, other )

i16.__add__ = i16__add__i16
i16.__wrapped_add__ = i16__wrapped_add__i16
i16.__saturated_add__ = i16__saturated_add__i16

@fallible_arithmetic
@private
@inline
def i16__sub__i16( value: i16, other: i16 ) -> Result[i16,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def i16__wrapped_sub__i16( value: i16, other: i16 ) -> i16:
	return compiler.wrapped_sub( value, other )

@private
@inline
def i16__saturated_sub__i16( value: i16, other: i16 ) -> i16:
	return compiler.saturated_sub( value, other )

i16.__sub__ = i16__sub__i16
i16.__wrapped_sub__ = i16__wrapped_sub__i16
i16.__saturated_sub__ = i16__saturated_sub__i16

@fallible_arithmetic
@private
@inline
def i16__mul__i16( value: i16, other: i16 ) -> Result[i16,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def i16__wrapped_mul__i16( value: i16, other: i16 ) -> i16:
	return compiler.wrapped_mul( value, other )

@private
@inline
def i16__saturated_mul__i16( value: i16, other: i16 ) -> i16:
	return compiler.saturated_mul( value, other )

i16.__mul__ = i16__mul__i16
i16.__wrapped_mul__ = i16__wrapped_mul__i16
i16.__saturated_mul__ = i16__saturated_mul__i16

@fallible_arithmetic
@private
@inline
def i32__add__i32( value: i32, other: i32 ) -> Result[i32,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def i32__wrapped_add__i32( value: i32, other: i32 ) -> i32:
	return compiler.wrapped_add( value, other )

@private
@inline
def i32__saturated_add__i32( value: i32, other: i32 ) -> i32:
	return compiler.saturated_add( value, other )

i32.__add__ = i32__add__i32
i32.__wrapped_add__ = i32__wrapped_add__i32
i32.__saturated_add__ = i32__saturated_add__i32

@fallible_arithmetic
@private
@inline
def i32__sub__i32( value: i32, other: i32 ) -> Result[i32,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def i32__wrapped_sub__i32( value: i32, other: i32 ) -> i32:
	return compiler.wrapped_sub( value, other )

@private
@inline
def i32__saturated_sub__i32( value: i32, other: i32 ) -> i32:
	return compiler.saturated_sub( value, other )

i32.__sub__ = i32__sub__i32
i32.__wrapped_sub__ = i32__wrapped_sub__i32
i32.__saturated_sub__ = i32__saturated_sub__i32

@fallible_arithmetic
@private
@inline
def i32__mul__i32( value: i32, other: i32 ) -> Result[i32,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def i32__wrapped_mul__i32( value: i32, other: i32 ) -> i32:
	return compiler.wrapped_mul( value, other )

@private
@inline
def i32__saturated_mul__i32( value: i32, other: i32 ) -> i32:
	return compiler.saturated_mul( value, other )

i32.__mul__ = i32__mul__i32
i32.__wrapped_mul__ = i32__wrapped_mul__i32
i32.__saturated_mul__ = i32__saturated_mul__i32

@fallible_arithmetic
@private
@inline
def i64__add__i64( value: i64, other: i64 ) -> Result[i64,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def i64__wrapped_add__i64( value: i64, other: i64 ) -> i64:
	return compiler.wrapped_add( value, other )

@private
@inline
def i64__saturated_add__i64( value: i64, other: i64 ) -> i64:
	return compiler.saturated_add( value, other )

i64.__add__ = i64__add__i64
i64.__wrapped_add__ = i64__wrapped_add__i64
i64.__saturated_add__ = i64__saturated_add__i64

@fallible_arithmetic
@private
@inline
def i64__sub__i64( value: i64, other: i64 ) -> Result[i64,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def i64__wrapped_sub__i64( value: i64, other: i64 ) -> i64:
	return compiler.wrapped_sub( value, other )

@private
@inline
def i64__saturated_sub__i64( value: i64, other: i64 ) -> i64:
	return compiler.saturated_sub( value, other )

i64.__sub__ = i64__sub__i64
i64.__wrapped_sub__ = i64__wrapped_sub__i64
i64.__saturated_sub__ = i64__saturated_sub__i64

@fallible_arithmetic
@private
@inline
def i64__mul__i64( value: i64, other: i64 ) -> Result[i64,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def i64__wrapped_mul__i64( value: i64, other: i64 ) -> i64:
	return compiler.wrapped_mul( value, other )

@private
@inline
def i64__saturated_mul__i64( value: i64, other: i64 ) -> i64:
	return compiler.saturated_mul( value, other )

i64.__mul__ = i64__mul__i64
i64.__wrapped_mul__ = i64__wrapped_mul__i64
i64.__saturated_mul__ = i64__saturated_mul__i64

@fallible_arithmetic
@private
@inline
def isize__add__isize( value: isize, other: isize ) -> Result[isize,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def isize__wrapped_add__isize( value: isize, other: isize ) -> isize:
	return compiler.wrapped_add( value, other )

@private
@inline
def isize__saturated_add__isize( value: isize, other: isize ) -> isize:
	return compiler.saturated_add( value, other )

isize.__add__ = isize__add__isize
isize.__wrapped_add__ = isize__wrapped_add__isize
isize.__saturated_add__ = isize__saturated_add__isize

@fallible_arithmetic
@private
@inline
def isize__sub__isize( value: isize, other: isize ) -> Result[isize,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def isize__wrapped_sub__isize( value: isize, other: isize ) -> isize:
	return compiler.wrapped_sub( value, other )

@private
@inline
def isize__saturated_sub__isize( value: isize, other: isize ) -> isize:
	return compiler.saturated_sub( value, other )

isize.__sub__ = isize__sub__isize
isize.__wrapped_sub__ = isize__wrapped_sub__isize
isize.__saturated_sub__ = isize__saturated_sub__isize

@fallible_arithmetic
@private
@inline
def isize__mul__isize( value: isize, other: isize ) -> Result[isize,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def isize__wrapped_mul__isize( value: isize, other: isize ) -> isize:
	return compiler.wrapped_mul( value, other )

@private
@inline
def isize__saturated_mul__isize( value: isize, other: isize ) -> isize:
	return compiler.saturated_mul( value, other )

isize.__mul__ = isize__mul__isize
isize.__wrapped_mul__ = isize__wrapped_mul__isize
isize.__saturated_mul__ = isize__saturated_mul__isize

@fallible_arithmetic
@private
@inline
def u8__add__u8( value: u8, other: u8 ) -> Result[u8,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def u8__wrapped_add__u8( value: u8, other: u8 ) -> u8:
	return compiler.wrapped_add( value, other )

@private
@inline
def u8__saturated_add__u8( value: u8, other: u8 ) -> u8:
	return compiler.saturated_add( value, other )

u8.__add__ = u8__add__u8
u8.__wrapped_add__ = u8__wrapped_add__u8
u8.__saturated_add__ = u8__saturated_add__u8

@fallible_arithmetic
@private
@inline
def u8__sub__u8( value: u8, other: u8 ) -> Result[u8,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def u8__wrapped_sub__u8( value: u8, other: u8 ) -> u8:
	return compiler.wrapped_sub( value, other )

@private
@inline
def u8__saturated_sub__u8( value: u8, other: u8 ) -> u8:
	return compiler.saturated_sub( value, other )

u8.__sub__ = u8__sub__u8
u8.__wrapped_sub__ = u8__wrapped_sub__u8
u8.__saturated_sub__ = u8__saturated_sub__u8

@fallible_arithmetic
@private
@inline
def u8__mul__u8( value: u8, other: u8 ) -> Result[u8,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def u8__wrapped_mul__u8( value: u8, other: u8 ) -> u8:
	return compiler.wrapped_mul( value, other )

@private
@inline
def u8__saturated_mul__u8( value: u8, other: u8 ) -> u8:
	return compiler.saturated_mul( value, other )

u8.__mul__ = u8__mul__u8
u8.__wrapped_mul__ = u8__wrapped_mul__u8
u8.__saturated_mul__ = u8__saturated_mul__u8

@fallible_arithmetic
@private
@inline
def u16__add__u16( value: u16, other: u16 ) -> Result[u16,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def u16__wrapped_add__u16( value: u16, other: u16 ) -> u16:
	return compiler.wrapped_add( value, other )

@private
@inline
def u16__saturated_add__u16( value: u16, other: u16 ) -> u16:
	return compiler.saturated_add( value, other )

u16.__add__ = u16__add__u16
u16.__wrapped_add__ = u16__wrapped_add__u16
u16.__saturated_add__ = u16__saturated_add__u16

@fallible_arithmetic
@private
@inline
def u16__sub__u16( value: u16, other: u16 ) -> Result[u16,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def u16__wrapped_sub__u16( value: u16, other: u16 ) -> u16:
	return compiler.wrapped_sub( value, other )

@private
@inline
def u16__saturated_sub__u16( value: u16, other: u16 ) -> u16:
	return compiler.saturated_sub( value, other )

u16.__sub__ = u16__sub__u16
u16.__wrapped_sub__ = u16__wrapped_sub__u16
u16.__saturated_sub__ = u16__saturated_sub__u16

@fallible_arithmetic
@private
@inline
def u16__mul__u16( value: u16, other: u16 ) -> Result[u16,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def u16__wrapped_mul__u16( value: u16, other: u16 ) -> u16:
	return compiler.wrapped_mul( value, other )

@private
@inline
def u16__saturated_mul__u16( value: u16, other: u16 ) -> u16:
	return compiler.saturated_mul( value, other )

u16.__mul__ = u16__mul__u16
u16.__wrapped_mul__ = u16__wrapped_mul__u16
u16.__saturated_mul__ = u16__saturated_mul__u16

@fallible_arithmetic
@private
@inline
def u32__add__u32( value: u32, other: u32 ) -> Result[u32,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def u32__wrapped_add__u32( value: u32, other: u32 ) -> u32:
	return compiler.wrapped_add( value, other )

@private
@inline
def u32__saturated_add__u32( value: u32, other: u32 ) -> u32:
	return compiler.saturated_add( value, other )

u32.__add__ = u32__add__u32
u32.__wrapped_add__ = u32__wrapped_add__u32
u32.__saturated_add__ = u32__saturated_add__u32

@fallible_arithmetic
@private
@inline
def u32__sub__u32( value: u32, other: u32 ) -> Result[u32,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def u32__wrapped_sub__u32( value: u32, other: u32 ) -> u32:
	return compiler.wrapped_sub( value, other )

@private
@inline
def u32__saturated_sub__u32( value: u32, other: u32 ) -> u32:
	return compiler.saturated_sub( value, other )

u32.__sub__ = u32__sub__u32
u32.__wrapped_sub__ = u32__wrapped_sub__u32
u32.__saturated_sub__ = u32__saturated_sub__u32

@fallible_arithmetic
@private
@inline
def u32__mul__u32( value: u32, other: u32 ) -> Result[u32,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def u32__wrapped_mul__u32( value: u32, other: u32 ) -> u32:
	return compiler.wrapped_mul( value, other )

@private
@inline
def u32__saturated_mul__u32( value: u32, other: u32 ) -> u32:
	return compiler.saturated_mul( value, other )

u32.__mul__ = u32__mul__u32
u32.__wrapped_mul__ = u32__wrapped_mul__u32
u32.__saturated_mul__ = u32__saturated_mul__u32

@fallible_arithmetic
@private
@inline
def u64__add__u64( value: u64, other: u64 ) -> Result[u64,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def u64__wrapped_add__u64( value: u64, other: u64 ) -> u64:
	return compiler.wrapped_add( value, other )

@private
@inline
def u64__saturated_add__u64( value: u64, other: u64 ) -> u64:
	return compiler.saturated_add( value, other )

u64.__add__ = u64__add__u64
u64.__wrapped_add__ = u64__wrapped_add__u64
u64.__saturated_add__ = u64__saturated_add__u64

@fallible_arithmetic
@private
@inline
def u64__sub__u64( value: u64, other: u64 ) -> Result[u64,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def u64__wrapped_sub__u64( value: u64, other: u64 ) -> u64:
	return compiler.wrapped_sub( value, other )

@private
@inline
def u64__saturated_sub__u64( value: u64, other: u64 ) -> u64:
	return compiler.saturated_sub( value, other )

u64.__sub__ = u64__sub__u64
u64.__wrapped_sub__ = u64__wrapped_sub__u64
u64.__saturated_sub__ = u64__saturated_sub__u64

@fallible_arithmetic
@private
@inline
def u64__mul__u64( value: u64, other: u64 ) -> Result[u64,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def u64__wrapped_mul__u64( value: u64, other: u64 ) -> u64:
	return compiler.wrapped_mul( value, other )

@private
@inline
def u64__saturated_mul__u64( value: u64, other: u64 ) -> u64:
	return compiler.saturated_mul( value, other )

u64.__mul__ = u64__mul__u64
u64.__wrapped_mul__ = u64__wrapped_mul__u64
u64.__saturated_mul__ = u64__saturated_mul__u64

@fallible_arithmetic
@private
@inline
def usize__add__usize( value: usize, other: usize ) -> Result[usize,OverflowError]:
	return compiler.checked_add( value, other )

@private
@inline
def usize__wrapped_add__usize( value: usize, other: usize ) -> usize:
	return compiler.wrapped_add( value, other )

@private
@inline
def usize__saturated_add__usize( value: usize, other: usize ) -> usize:
	return compiler.saturated_add( value, other )

usize.__add__ = usize__add__usize
usize.__wrapped_add__ = usize__wrapped_add__usize
usize.__saturated_add__ = usize__saturated_add__usize

@fallible_arithmetic
@private
@inline
def usize__sub__usize( value: usize, other: usize ) -> Result[usize,OverflowError]:
	return compiler.checked_sub( value, other )

@private
@inline
def usize__wrapped_sub__usize( value: usize, other: usize ) -> usize:
	return compiler.wrapped_sub( value, other )

@private
@inline
def usize__saturated_sub__usize( value: usize, other: usize ) -> usize:
	return compiler.saturated_sub( value, other )

usize.__sub__ = usize__sub__usize
usize.__wrapped_sub__ = usize__wrapped_sub__usize
usize.__saturated_sub__ = usize__saturated_sub__usize

@fallible_arithmetic
@private
@inline
def usize__mul__usize( value: usize, other: usize ) -> Result[usize,OverflowError]:
	return compiler.checked_mul( value, other )

@private
@inline
def usize__wrapped_mul__usize( value: usize, other: usize ) -> usize:
	return compiler.wrapped_mul( value, other )

@private
@inline
def usize__saturated_mul__usize( value: usize, other: usize ) -> usize:
	return compiler.saturated_mul( value, other )

usize.__mul__ = usize__mul__usize
usize.__wrapped_mul__ = usize__wrapped_mul__usize
usize.__saturated_mul__ = usize__saturated_mul__usize

@fallible_arithmetic
@private
@inline
def i8__floordiv__i8( value: i8, other: i8 ) -> Result[i8,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i8__wrapped_floordiv__i8( value: i8, other: i8 ) -> Result[i8,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i8__saturated_floordiv__i8( value: i8, other: i8 ) -> Result[i8,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

i8.__floordiv__ = i8__floordiv__i8
i8.__wrapped_floordiv__ = i8__wrapped_floordiv__i8
i8.__saturated_floordiv__ = i8__saturated_floordiv__i8

@fallible_arithmetic
@private
@inline
def i8__mod__i8( value: i8, other: i8 ) -> Result[i8,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def i8__wrapped_mod__i8( value: i8, other: i8 ) -> Result[i8,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def i8__saturated_mod__i8( value: i8, other: i8 ) -> Result[i8,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

i8.__mod__ = i8__mod__i8
i8.__wrapped_mod__ = i8__wrapped_mod__i8
i8.__saturated_mod__ = i8__saturated_mod__i8

@fallible_arithmetic
@private
@inline
def i16__floordiv__i16( value: i16, other: i16 ) -> Result[i16,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i16__wrapped_floordiv__i16( value: i16, other: i16 ) -> Result[i16,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i16__saturated_floordiv__i16( value: i16, other: i16 ) -> Result[i16,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

i16.__floordiv__ = i16__floordiv__i16
i16.__wrapped_floordiv__ = i16__wrapped_floordiv__i16
i16.__saturated_floordiv__ = i16__saturated_floordiv__i16

@fallible_arithmetic
@private
@inline
def i16__mod__i16( value: i16, other: i16 ) -> Result[i16,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def i16__wrapped_mod__i16( value: i16, other: i16 ) -> Result[i16,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def i16__saturated_mod__i16( value: i16, other: i16 ) -> Result[i16,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

i16.__mod__ = i16__mod__i16
i16.__wrapped_mod__ = i16__wrapped_mod__i16
i16.__saturated_mod__ = i16__saturated_mod__i16

@fallible_arithmetic
@private
@inline
def i32__floordiv__i32( value: i32, other: i32 ) -> Result[i32,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i32__wrapped_floordiv__i32( value: i32, other: i32 ) -> Result[i32,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i32__saturated_floordiv__i32( value: i32, other: i32 ) -> Result[i32,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

i32.__floordiv__ = i32__floordiv__i32
i32.__wrapped_floordiv__ = i32__wrapped_floordiv__i32
i32.__saturated_floordiv__ = i32__saturated_floordiv__i32

@fallible_arithmetic
@private
@inline
def i32__mod__i32( value: i32, other: i32 ) -> Result[i32,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def i32__wrapped_mod__i32( value: i32, other: i32 ) -> Result[i32,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def i32__saturated_mod__i32( value: i32, other: i32 ) -> Result[i32,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

i32.__mod__ = i32__mod__i32
i32.__wrapped_mod__ = i32__wrapped_mod__i32
i32.__saturated_mod__ = i32__saturated_mod__i32

@fallible_arithmetic
@private
@inline
def i64__floordiv__i64( value: i64, other: i64 ) -> Result[i64,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i64__wrapped_floordiv__i64( value: i64, other: i64 ) -> Result[i64,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def i64__saturated_floordiv__i64( value: i64, other: i64 ) -> Result[i64,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

i64.__floordiv__ = i64__floordiv__i64
i64.__wrapped_floordiv__ = i64__wrapped_floordiv__i64
i64.__saturated_floordiv__ = i64__saturated_floordiv__i64

@fallible_arithmetic
@private
@inline
def i64__mod__i64( value: i64, other: i64 ) -> Result[i64,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def i64__wrapped_mod__i64( value: i64, other: i64 ) -> Result[i64,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def i64__saturated_mod__i64( value: i64, other: i64 ) -> Result[i64,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

i64.__mod__ = i64__mod__i64
i64.__wrapped_mod__ = i64__wrapped_mod__i64
i64.__saturated_mod__ = i64__saturated_mod__i64

@fallible_arithmetic
@private
@inline
def isize__floordiv__isize( value: isize, other: isize ) -> Result[isize,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def isize__wrapped_floordiv__isize( value: isize, other: isize ) -> Result[isize,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def isize__saturated_floordiv__isize( value: isize, other: isize ) -> Result[isize,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

isize.__floordiv__ = isize__floordiv__isize
isize.__wrapped_floordiv__ = isize__wrapped_floordiv__isize
isize.__saturated_floordiv__ = isize__saturated_floordiv__isize

@fallible_arithmetic
@private
@inline
def isize__mod__isize( value: isize, other: isize ) -> Result[isize,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def isize__wrapped_mod__isize( value: isize, other: isize ) -> Result[isize,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def isize__saturated_mod__isize( value: isize, other: isize ) -> Result[isize,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

isize.__mod__ = isize__mod__isize
isize.__wrapped_mod__ = isize__wrapped_mod__isize
isize.__saturated_mod__ = isize__saturated_mod__isize

@fallible_arithmetic
@private
@inline
def u8__floordiv__u8( value: u8, other: u8 ) -> Result[u8,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u8__wrapped_floordiv__u8( value: u8, other: u8 ) -> Result[u8,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u8__saturated_floordiv__u8( value: u8, other: u8 ) -> Result[u8,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

u8.__floordiv__ = u8__floordiv__u8
u8.__wrapped_floordiv__ = u8__wrapped_floordiv__u8
u8.__saturated_floordiv__ = u8__saturated_floordiv__u8

@fallible_arithmetic
@private
@inline
def u8__mod__u8( value: u8, other: u8 ) -> Result[u8,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def u8__wrapped_mod__u8( value: u8, other: u8 ) -> Result[u8,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def u8__saturated_mod__u8( value: u8, other: u8 ) -> Result[u8,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

u8.__mod__ = u8__mod__u8
u8.__wrapped_mod__ = u8__wrapped_mod__u8
u8.__saturated_mod__ = u8__saturated_mod__u8

@fallible_arithmetic
@private
@inline
def u16__floordiv__u16( value: u16, other: u16 ) -> Result[u16,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u16__wrapped_floordiv__u16( value: u16, other: u16 ) -> Result[u16,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u16__saturated_floordiv__u16( value: u16, other: u16 ) -> Result[u16,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

u16.__floordiv__ = u16__floordiv__u16
u16.__wrapped_floordiv__ = u16__wrapped_floordiv__u16
u16.__saturated_floordiv__ = u16__saturated_floordiv__u16

@fallible_arithmetic
@private
@inline
def u16__mod__u16( value: u16, other: u16 ) -> Result[u16,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def u16__wrapped_mod__u16( value: u16, other: u16 ) -> Result[u16,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def u16__saturated_mod__u16( value: u16, other: u16 ) -> Result[u16,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

u16.__mod__ = u16__mod__u16
u16.__wrapped_mod__ = u16__wrapped_mod__u16
u16.__saturated_mod__ = u16__saturated_mod__u16

@fallible_arithmetic
@private
@inline
def u32__floordiv__u32( value: u32, other: u32 ) -> Result[u32,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u32__wrapped_floordiv__u32( value: u32, other: u32 ) -> Result[u32,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u32__saturated_floordiv__u32( value: u32, other: u32 ) -> Result[u32,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

u32.__floordiv__ = u32__floordiv__u32
u32.__wrapped_floordiv__ = u32__wrapped_floordiv__u32
u32.__saturated_floordiv__ = u32__saturated_floordiv__u32

@fallible_arithmetic
@private
@inline
def u32__mod__u32( value: u32, other: u32 ) -> Result[u32,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def u32__wrapped_mod__u32( value: u32, other: u32 ) -> Result[u32,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def u32__saturated_mod__u32( value: u32, other: u32 ) -> Result[u32,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

u32.__mod__ = u32__mod__u32
u32.__wrapped_mod__ = u32__wrapped_mod__u32
u32.__saturated_mod__ = u32__saturated_mod__u32

@fallible_arithmetic
@private
@inline
def u64__floordiv__u64( value: u64, other: u64 ) -> Result[u64,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u64__wrapped_floordiv__u64( value: u64, other: u64 ) -> Result[u64,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def u64__saturated_floordiv__u64( value: u64, other: u64 ) -> Result[u64,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

u64.__floordiv__ = u64__floordiv__u64
u64.__wrapped_floordiv__ = u64__wrapped_floordiv__u64
u64.__saturated_floordiv__ = u64__saturated_floordiv__u64

@fallible_arithmetic
@private
@inline
def u64__mod__u64( value: u64, other: u64 ) -> Result[u64,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def u64__wrapped_mod__u64( value: u64, other: u64 ) -> Result[u64,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def u64__saturated_mod__u64( value: u64, other: u64 ) -> Result[u64,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

u64.__mod__ = u64__mod__u64
u64.__wrapped_mod__ = u64__wrapped_mod__u64
u64.__saturated_mod__ = u64__saturated_mod__u64

@fallible_arithmetic
@private
@inline
def usize__floordiv__usize( value: usize, other: usize ) -> Result[usize,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def usize__wrapped_floordiv__usize( value: usize, other: usize ) -> Result[usize,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@private
@inline
def usize__saturated_floordiv__usize( value: usize, other: usize ) -> Result[usize,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

usize.__floordiv__ = usize__floordiv__usize
usize.__wrapped_floordiv__ = usize__wrapped_floordiv__usize
usize.__saturated_floordiv__ = usize__saturated_floordiv__usize

@fallible_arithmetic
@private
@inline
def usize__mod__usize( value: usize, other: usize ) -> Result[usize,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@private
@inline
def usize__wrapped_mod__usize( value: usize, other: usize ) -> Result[usize,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@private
@inline
def usize__saturated_mod__usize( value: usize, other: usize ) -> Result[usize,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

usize.__mod__ = usize__mod__usize
usize.__wrapped_mod__ = usize__wrapped_mod__usize
usize.__saturated_mod__ = usize__saturated_mod__usize

@fallible_arithmetic
@private
@inline
def f32__add__f32( value: f32, other: f32 ) -> Result[f32,FloatingPointError]:
	return compiler.checked_add( value, other )

@private
@inline
def f32__wrapped_add__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_add( value, other )

@private
@inline
def f32__saturated_add__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_add( value, other )

f32.__add__ = f32__add__f32
f32.__wrapped_add__ = f32__wrapped_add__f32
f32.__saturated_add__ = f32__saturated_add__f32

@fallible_arithmetic
@private
@inline
def f32__sub__f32( value: f32, other: f32 ) -> Result[f32,FloatingPointError]:
	return compiler.checked_sub( value, other )

@private
@inline
def f32__wrapped_sub__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_sub( value, other )

@private
@inline
def f32__saturated_sub__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_sub( value, other )

f32.__sub__ = f32__sub__f32
f32.__wrapped_sub__ = f32__wrapped_sub__f32
f32.__saturated_sub__ = f32__saturated_sub__f32

@fallible_arithmetic
@private
@inline
def f32__mul__f32( value: f32, other: f32 ) -> Result[f32,FloatingPointError]:
	return compiler.checked_mul( value, other )

@private
@inline
def f32__wrapped_mul__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_mul( value, other )

@private
@inline
def f32__saturated_mul__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_mul( value, other )

f32.__mul__ = f32__mul__f32
f32.__wrapped_mul__ = f32__wrapped_mul__f32
f32.__saturated_mul__ = f32__saturated_mul__f32

@fallible_arithmetic
@private
@inline
def f64__add__f64( value: f64, other: f64 ) -> Result[f64,FloatingPointError]:
	return compiler.checked_add( value, other )

@private
@inline
def f64__wrapped_add__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_add( value, other )

@private
@inline
def f64__saturated_add__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_add( value, other )

f64.__add__ = f64__add__f64
f64.__wrapped_add__ = f64__wrapped_add__f64
f64.__saturated_add__ = f64__saturated_add__f64

@fallible_arithmetic
@private
@inline
def f64__sub__f64( value: f64, other: f64 ) -> Result[f64,FloatingPointError]:
	return compiler.checked_sub( value, other )

@private
@inline
def f64__wrapped_sub__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_sub( value, other )

@private
@inline
def f64__saturated_sub__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_sub( value, other )

f64.__sub__ = f64__sub__f64
f64.__wrapped_sub__ = f64__wrapped_sub__f64
f64.__saturated_sub__ = f64__saturated_sub__f64

@fallible_arithmetic
@private
@inline
def f64__mul__f64( value: f64, other: f64 ) -> Result[f64,FloatingPointError]:
	return compiler.checked_mul( value, other )

@private
@inline
def f64__wrapped_mul__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_mul( value, other )

@private
@inline
def f64__saturated_mul__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_mul( value, other )

f64.__mul__ = f64__mul__f64
f64.__wrapped_mul__ = f64__wrapped_mul__f64
f64.__saturated_mul__ = f64__saturated_mul__f64

@fallible_arithmetic
@private
@inline
def f32__truediv__f32( value: f32, other: f32 ) -> Result[f32,ZeroDivisionError|FloatingPointError]:
	return compiler.checked_truediv( value, other )

@private
@inline
def f32__wrapped_truediv__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_truediv( value, other )

@private
@inline
def f32__saturated_truediv__f32( value: f32, other: f32 ) -> f32:
	return compiler.wrapped_truediv( value, other )

f32.__truediv__ = f32__truediv__f32
f32.__wrapped_truediv__ = f32__wrapped_truediv__f32
f32.__saturated_truediv__ = f32__saturated_truediv__f32

@fallible_arithmetic
@private
@inline
def f64__truediv__f64( value: f64, other: f64 ) -> Result[f64,ZeroDivisionError|FloatingPointError]:
	return compiler.checked_truediv( value, other )

@private
@inline
def f64__wrapped_truediv__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_truediv( value, other )

@private
@inline
def f64__saturated_truediv__f64( value: f64, other: f64 ) -> f64:
	return compiler.wrapped_truediv( value, other )

f64.__truediv__ = f64__truediv__f64
f64.__wrapped_truediv__ = f64__wrapped_truediv__f64
f64.__saturated_truediv__ = f64__saturated_truediv__f64
