# GENERATED by gen_scalar_dunders.py - do not hand-edit; re-run the
# generator instead. One real generic function body per (operator,
# mode) pair (see that script's own header comment), specialized per
# concrete scalar type via one registration line each below.

@fallible_arithmetic
@inline
def i_add_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_add( value, other )

@inline
def i_add_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_add( value, other )

@inline
def i_add_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_add( value, other )

@fallible_arithmetic
@inline
def i_sub_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_sub( value, other )

@inline
def i_sub_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_sub( value, other )

@inline
def i_sub_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_sub( value, other )

@fallible_arithmetic
@inline
def i_mul_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_mul( value, other )

@inline
def i_mul_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_mul( value, other )

@inline
def i_mul_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_mul( value, other )

@fallible_arithmetic
@inline
def i_floordiv_checked_signed[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@inline
def i_floordiv_checked_unsigned[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@inline
def i_floordiv_wrapped[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@inline
def i_floordiv_saturated[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

@fallible_arithmetic
@inline
def i_mod_checked_signed[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@inline
def i_mod_checked_unsigned[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@inline
def i_mod_wrapped[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@inline
def i_mod_saturated[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

@fallible_arithmetic
@inline
def f_add_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:
	return compiler.checked_add( value, other )

@inline
def f_add_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_add( value, other )

@inline
def f_add_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_add( value, other )

@fallible_arithmetic
@inline
def f_sub_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:
	return compiler.checked_sub( value, other )

@inline
def f_sub_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_sub( value, other )

@inline
def f_sub_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_sub( value, other )

@fallible_arithmetic
@inline
def f_mul_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:
	return compiler.checked_mul( value, other )

@inline
def f_mul_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_mul( value, other )

@inline
def f_mul_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_mul( value, other )

@fallible_arithmetic
@inline
def f_truediv_checked[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|FloatingPointError]:
	return compiler.checked_truediv( value, other )

@inline
def f_truediv_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_truediv( value, other )

@inline
def f_truediv_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_truediv( value, other )

@inline
def i_and[T]( value: T, other: T ) -> T:
	return compiler.bitand( value, other )

@inline
def i_or[T]( value: T, other: T ) -> T:
	return compiler.bitor( value, other )

@inline
def i_xor[T]( value: T, other: T ) -> T:
	return compiler.bitxor( value, other )

@fallible_arithmetic
@inline
def i_shl_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_shl( value, other )

@inline
def i_shl_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_shl( value, other )

@inline
def i_shl_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_shl( value, other )

@inline
def i_rshift[T]( value: T, other: T ) -> T:
	return compiler.rshift( value, other )

# --- int add/sub/mul -----------------------------------------------

i8.__add__ = i_add_checked[i8]
i8.__wrapped_add__ = i_add_wrapped[i8]
i8.__saturated_add__ = i_add_saturated[i8]
i8.__sub__ = i_sub_checked[i8]
i8.__wrapped_sub__ = i_sub_wrapped[i8]
i8.__saturated_sub__ = i_sub_saturated[i8]
i8.__mul__ = i_mul_checked[i8]
i8.__wrapped_mul__ = i_mul_wrapped[i8]
i8.__saturated_mul__ = i_mul_saturated[i8]

i16.__add__ = i_add_checked[i16]
i16.__wrapped_add__ = i_add_wrapped[i16]
i16.__saturated_add__ = i_add_saturated[i16]
i16.__sub__ = i_sub_checked[i16]
i16.__wrapped_sub__ = i_sub_wrapped[i16]
i16.__saturated_sub__ = i_sub_saturated[i16]
i16.__mul__ = i_mul_checked[i16]
i16.__wrapped_mul__ = i_mul_wrapped[i16]
i16.__saturated_mul__ = i_mul_saturated[i16]

i32.__add__ = i_add_checked[i32]
i32.__wrapped_add__ = i_add_wrapped[i32]
i32.__saturated_add__ = i_add_saturated[i32]
i32.__sub__ = i_sub_checked[i32]
i32.__wrapped_sub__ = i_sub_wrapped[i32]
i32.__saturated_sub__ = i_sub_saturated[i32]
i32.__mul__ = i_mul_checked[i32]
i32.__wrapped_mul__ = i_mul_wrapped[i32]
i32.__saturated_mul__ = i_mul_saturated[i32]

i64.__add__ = i_add_checked[i64]
i64.__wrapped_add__ = i_add_wrapped[i64]
i64.__saturated_add__ = i_add_saturated[i64]
i64.__sub__ = i_sub_checked[i64]
i64.__wrapped_sub__ = i_sub_wrapped[i64]
i64.__saturated_sub__ = i_sub_saturated[i64]
i64.__mul__ = i_mul_checked[i64]
i64.__wrapped_mul__ = i_mul_wrapped[i64]
i64.__saturated_mul__ = i_mul_saturated[i64]

i128.__add__ = i_add_checked[i128]
i128.__wrapped_add__ = i_add_wrapped[i128]
i128.__saturated_add__ = i_add_saturated[i128]
i128.__sub__ = i_sub_checked[i128]
i128.__wrapped_sub__ = i_sub_wrapped[i128]
i128.__saturated_sub__ = i_sub_saturated[i128]
i128.__mul__ = i_mul_checked[i128]
i128.__wrapped_mul__ = i_mul_wrapped[i128]
i128.__saturated_mul__ = i_mul_saturated[i128]

isize.__add__ = i_add_checked[isize]
isize.__wrapped_add__ = i_add_wrapped[isize]
isize.__saturated_add__ = i_add_saturated[isize]
isize.__sub__ = i_sub_checked[isize]
isize.__wrapped_sub__ = i_sub_wrapped[isize]
isize.__saturated_sub__ = i_sub_saturated[isize]
isize.__mul__ = i_mul_checked[isize]
isize.__wrapped_mul__ = i_mul_wrapped[isize]
isize.__saturated_mul__ = i_mul_saturated[isize]

u8.__add__ = i_add_checked[u8]
u8.__wrapped_add__ = i_add_wrapped[u8]
u8.__saturated_add__ = i_add_saturated[u8]
u8.__sub__ = i_sub_checked[u8]
u8.__wrapped_sub__ = i_sub_wrapped[u8]
u8.__saturated_sub__ = i_sub_saturated[u8]
u8.__mul__ = i_mul_checked[u8]
u8.__wrapped_mul__ = i_mul_wrapped[u8]
u8.__saturated_mul__ = i_mul_saturated[u8]

u16.__add__ = i_add_checked[u16]
u16.__wrapped_add__ = i_add_wrapped[u16]
u16.__saturated_add__ = i_add_saturated[u16]
u16.__sub__ = i_sub_checked[u16]
u16.__wrapped_sub__ = i_sub_wrapped[u16]
u16.__saturated_sub__ = i_sub_saturated[u16]
u16.__mul__ = i_mul_checked[u16]
u16.__wrapped_mul__ = i_mul_wrapped[u16]
u16.__saturated_mul__ = i_mul_saturated[u16]

u32.__add__ = i_add_checked[u32]
u32.__wrapped_add__ = i_add_wrapped[u32]
u32.__saturated_add__ = i_add_saturated[u32]
u32.__sub__ = i_sub_checked[u32]
u32.__wrapped_sub__ = i_sub_wrapped[u32]
u32.__saturated_sub__ = i_sub_saturated[u32]
u32.__mul__ = i_mul_checked[u32]
u32.__wrapped_mul__ = i_mul_wrapped[u32]
u32.__saturated_mul__ = i_mul_saturated[u32]

u64.__add__ = i_add_checked[u64]
u64.__wrapped_add__ = i_add_wrapped[u64]
u64.__saturated_add__ = i_add_saturated[u64]
u64.__sub__ = i_sub_checked[u64]
u64.__wrapped_sub__ = i_sub_wrapped[u64]
u64.__saturated_sub__ = i_sub_saturated[u64]
u64.__mul__ = i_mul_checked[u64]
u64.__wrapped_mul__ = i_mul_wrapped[u64]
u64.__saturated_mul__ = i_mul_saturated[u64]

u128.__add__ = i_add_checked[u128]
u128.__wrapped_add__ = i_add_wrapped[u128]
u128.__saturated_add__ = i_add_saturated[u128]
u128.__sub__ = i_sub_checked[u128]
u128.__wrapped_sub__ = i_sub_wrapped[u128]
u128.__saturated_sub__ = i_sub_saturated[u128]
u128.__mul__ = i_mul_checked[u128]
u128.__wrapped_mul__ = i_mul_wrapped[u128]
u128.__saturated_mul__ = i_mul_saturated[u128]

usize.__add__ = i_add_checked[usize]
usize.__wrapped_add__ = i_add_wrapped[usize]
usize.__saturated_add__ = i_add_saturated[usize]
usize.__sub__ = i_sub_checked[usize]
usize.__wrapped_sub__ = i_sub_wrapped[usize]
usize.__saturated_sub__ = i_sub_saturated[usize]
usize.__mul__ = i_mul_checked[usize]
usize.__wrapped_mul__ = i_mul_wrapped[usize]
usize.__saturated_mul__ = i_mul_saturated[usize]

# --- int floordiv/mod -----------------------------------------------

i8.__floordiv__ = i_floordiv_checked_signed[i8]
i8.__wrapped_floordiv__ = i_floordiv_wrapped[i8]
i8.__saturated_floordiv__ = i_floordiv_saturated[i8]
i8.__mod__ = i_mod_checked_signed[i8]
i8.__wrapped_mod__ = i_mod_wrapped[i8]
i8.__saturated_mod__ = i_mod_saturated[i8]

i16.__floordiv__ = i_floordiv_checked_signed[i16]
i16.__wrapped_floordiv__ = i_floordiv_wrapped[i16]
i16.__saturated_floordiv__ = i_floordiv_saturated[i16]
i16.__mod__ = i_mod_checked_signed[i16]
i16.__wrapped_mod__ = i_mod_wrapped[i16]
i16.__saturated_mod__ = i_mod_saturated[i16]

i32.__floordiv__ = i_floordiv_checked_signed[i32]
i32.__wrapped_floordiv__ = i_floordiv_wrapped[i32]
i32.__saturated_floordiv__ = i_floordiv_saturated[i32]
i32.__mod__ = i_mod_checked_signed[i32]
i32.__wrapped_mod__ = i_mod_wrapped[i32]
i32.__saturated_mod__ = i_mod_saturated[i32]

i64.__floordiv__ = i_floordiv_checked_signed[i64]
i64.__wrapped_floordiv__ = i_floordiv_wrapped[i64]
i64.__saturated_floordiv__ = i_floordiv_saturated[i64]
i64.__mod__ = i_mod_checked_signed[i64]
i64.__wrapped_mod__ = i_mod_wrapped[i64]
i64.__saturated_mod__ = i_mod_saturated[i64]

i128.__floordiv__ = i_floordiv_checked_signed[i128]
i128.__wrapped_floordiv__ = i_floordiv_wrapped[i128]
i128.__saturated_floordiv__ = i_floordiv_saturated[i128]
i128.__mod__ = i_mod_checked_signed[i128]
i128.__wrapped_mod__ = i_mod_wrapped[i128]
i128.__saturated_mod__ = i_mod_saturated[i128]

isize.__floordiv__ = i_floordiv_checked_signed[isize]
isize.__wrapped_floordiv__ = i_floordiv_wrapped[isize]
isize.__saturated_floordiv__ = i_floordiv_saturated[isize]
isize.__mod__ = i_mod_checked_signed[isize]
isize.__wrapped_mod__ = i_mod_wrapped[isize]
isize.__saturated_mod__ = i_mod_saturated[isize]

u8.__floordiv__ = i_floordiv_checked_unsigned[u8]
u8.__wrapped_floordiv__ = i_floordiv_wrapped[u8]
u8.__saturated_floordiv__ = i_floordiv_saturated[u8]
u8.__mod__ = i_mod_checked_unsigned[u8]
u8.__wrapped_mod__ = i_mod_wrapped[u8]
u8.__saturated_mod__ = i_mod_saturated[u8]

u16.__floordiv__ = i_floordiv_checked_unsigned[u16]
u16.__wrapped_floordiv__ = i_floordiv_wrapped[u16]
u16.__saturated_floordiv__ = i_floordiv_saturated[u16]
u16.__mod__ = i_mod_checked_unsigned[u16]
u16.__wrapped_mod__ = i_mod_wrapped[u16]
u16.__saturated_mod__ = i_mod_saturated[u16]

u32.__floordiv__ = i_floordiv_checked_unsigned[u32]
u32.__wrapped_floordiv__ = i_floordiv_wrapped[u32]
u32.__saturated_floordiv__ = i_floordiv_saturated[u32]
u32.__mod__ = i_mod_checked_unsigned[u32]
u32.__wrapped_mod__ = i_mod_wrapped[u32]
u32.__saturated_mod__ = i_mod_saturated[u32]

u64.__floordiv__ = i_floordiv_checked_unsigned[u64]
u64.__wrapped_floordiv__ = i_floordiv_wrapped[u64]
u64.__saturated_floordiv__ = i_floordiv_saturated[u64]
u64.__mod__ = i_mod_checked_unsigned[u64]
u64.__wrapped_mod__ = i_mod_wrapped[u64]
u64.__saturated_mod__ = i_mod_saturated[u64]

u128.__floordiv__ = i_floordiv_checked_unsigned[u128]
u128.__wrapped_floordiv__ = i_floordiv_wrapped[u128]
u128.__saturated_floordiv__ = i_floordiv_saturated[u128]
u128.__mod__ = i_mod_checked_unsigned[u128]
u128.__wrapped_mod__ = i_mod_wrapped[u128]
u128.__saturated_mod__ = i_mod_saturated[u128]

usize.__floordiv__ = i_floordiv_checked_unsigned[usize]
usize.__wrapped_floordiv__ = i_floordiv_wrapped[usize]
usize.__saturated_floordiv__ = i_floordiv_saturated[usize]
usize.__mod__ = i_mod_checked_unsigned[usize]
usize.__wrapped_mod__ = i_mod_wrapped[usize]
usize.__saturated_mod__ = i_mod_saturated[usize]

# --- float add/sub/mul ----------------------------------------------

f32.__add__ = f_add_checked[f32]
f32.__wrapped_add__ = f_add_wrapped[f32]
f32.__saturated_add__ = f_add_saturated[f32]
f32.__sub__ = f_sub_checked[f32]
f32.__wrapped_sub__ = f_sub_wrapped[f32]
f32.__saturated_sub__ = f_sub_saturated[f32]
f32.__mul__ = f_mul_checked[f32]
f32.__wrapped_mul__ = f_mul_wrapped[f32]
f32.__saturated_mul__ = f_mul_saturated[f32]

f64.__add__ = f_add_checked[f64]
f64.__wrapped_add__ = f_add_wrapped[f64]
f64.__saturated_add__ = f_add_saturated[f64]
f64.__sub__ = f_sub_checked[f64]
f64.__wrapped_sub__ = f_sub_wrapped[f64]
f64.__saturated_sub__ = f_sub_saturated[f64]
f64.__mul__ = f_mul_checked[f64]
f64.__wrapped_mul__ = f_mul_wrapped[f64]
f64.__saturated_mul__ = f_mul_saturated[f64]

# --- float truediv ---------------------------------------------------

f32.__truediv__ = f_truediv_checked[f32]
f32.__wrapped_truediv__ = f_truediv_wrapped[f32]
f32.__saturated_truediv__ = f_truediv_saturated[f32]
f64.__truediv__ = f_truediv_checked[f64]
f64.__wrapped_truediv__ = f_truediv_wrapped[f64]
f64.__saturated_truediv__ = f_truediv_saturated[f64]

# --- int/bool bitwise (&/|/^) - single variant, no mode qualification -

i8.__and__ = i_and[i8]
i8.__or__ = i_or[i8]
i8.__xor__ = i_xor[i8]
i16.__and__ = i_and[i16]
i16.__or__ = i_or[i16]
i16.__xor__ = i_xor[i16]
i32.__and__ = i_and[i32]
i32.__or__ = i_or[i32]
i32.__xor__ = i_xor[i32]
i64.__and__ = i_and[i64]
i64.__or__ = i_or[i64]
i64.__xor__ = i_xor[i64]
i128.__and__ = i_and[i128]
i128.__or__ = i_or[i128]
i128.__xor__ = i_xor[i128]
isize.__and__ = i_and[isize]
isize.__or__ = i_or[isize]
isize.__xor__ = i_xor[isize]
u8.__and__ = i_and[u8]
u8.__or__ = i_or[u8]
u8.__xor__ = i_xor[u8]
u16.__and__ = i_and[u16]
u16.__or__ = i_or[u16]
u16.__xor__ = i_xor[u16]
u32.__and__ = i_and[u32]
u32.__or__ = i_or[u32]
u32.__xor__ = i_xor[u32]
u64.__and__ = i_and[u64]
u64.__or__ = i_or[u64]
u64.__xor__ = i_xor[u64]
u128.__and__ = i_and[u128]
u128.__or__ = i_or[u128]
u128.__xor__ = i_xor[u128]
usize.__and__ = i_and[usize]
usize.__or__ = i_or[usize]
usize.__xor__ = i_xor[usize]
bool.__and__ = i_and[bool]
bool.__or__ = i_or[bool]
bool.__xor__ = i_xor[bool]

# --- int shifts (<< checked/wrapped/saturated, >> single variant) ---

i8.__lshift__ = i_shl_checked[i8]
i8.__wrapped_lshift__ = i_shl_wrapped[i8]
i8.__saturated_lshift__ = i_shl_saturated[i8]
i8.__rshift__ = i_rshift[i8]
i16.__lshift__ = i_shl_checked[i16]
i16.__wrapped_lshift__ = i_shl_wrapped[i16]
i16.__saturated_lshift__ = i_shl_saturated[i16]
i16.__rshift__ = i_rshift[i16]
i32.__lshift__ = i_shl_checked[i32]
i32.__wrapped_lshift__ = i_shl_wrapped[i32]
i32.__saturated_lshift__ = i_shl_saturated[i32]
i32.__rshift__ = i_rshift[i32]
i64.__lshift__ = i_shl_checked[i64]
i64.__wrapped_lshift__ = i_shl_wrapped[i64]
i64.__saturated_lshift__ = i_shl_saturated[i64]
i64.__rshift__ = i_rshift[i64]
i128.__lshift__ = i_shl_checked[i128]
i128.__wrapped_lshift__ = i_shl_wrapped[i128]
i128.__saturated_lshift__ = i_shl_saturated[i128]
i128.__rshift__ = i_rshift[i128]
isize.__lshift__ = i_shl_checked[isize]
isize.__wrapped_lshift__ = i_shl_wrapped[isize]
isize.__saturated_lshift__ = i_shl_saturated[isize]
isize.__rshift__ = i_rshift[isize]
u8.__lshift__ = i_shl_checked[u8]
u8.__wrapped_lshift__ = i_shl_wrapped[u8]
u8.__saturated_lshift__ = i_shl_saturated[u8]
u8.__rshift__ = i_rshift[u8]
u16.__lshift__ = i_shl_checked[u16]
u16.__wrapped_lshift__ = i_shl_wrapped[u16]
u16.__saturated_lshift__ = i_shl_saturated[u16]
u16.__rshift__ = i_rshift[u16]
u32.__lshift__ = i_shl_checked[u32]
u32.__wrapped_lshift__ = i_shl_wrapped[u32]
u32.__saturated_lshift__ = i_shl_saturated[u32]
u32.__rshift__ = i_rshift[u32]
u64.__lshift__ = i_shl_checked[u64]
u64.__wrapped_lshift__ = i_shl_wrapped[u64]
u64.__saturated_lshift__ = i_shl_saturated[u64]
u64.__rshift__ = i_rshift[u64]
u128.__lshift__ = i_shl_checked[u128]
u128.__wrapped_lshift__ = i_shl_wrapped[u128]
u128.__saturated_lshift__ = i_shl_saturated[u128]
u128.__rshift__ = i_rshift[u128]
usize.__lshift__ = i_shl_checked[usize]
usize.__wrapped_lshift__ = i_shl_wrapped[usize]
usize.__saturated_lshift__ = i_shl_saturated[usize]
usize.__rshift__ = i_rshift[usize]

@inline
def scalar_eq[T]( value: T, other: T ) -> bool:
	return compiler.cmp_eq( value, other )

@inline
def scalar_ne[T]( value: T, other: T ) -> bool:
	return compiler.cmp_ne( value, other )

@inline
def scalar_lt[T]( value: T, other: T ) -> bool:
	return compiler.cmp_lt( value, other )

@inline
def scalar_le[T]( value: T, other: T ) -> bool:
	return compiler.cmp_le( value, other )

@inline
def scalar_gt[T]( value: T, other: T ) -> bool:
	return compiler.cmp_gt( value, other )

@inline
def scalar_ge[T]( value: T, other: T ) -> bool:
	return compiler.cmp_ge( value, other )

# --- comparisons (==, !=, <, <=, >, >=) -------------------------------

i8.__eq__ = scalar_eq[i8]
i8.__ne__ = scalar_ne[i8]
i8.__lt__ = scalar_lt[i8]
i8.__le__ = scalar_le[i8]
i8.__gt__ = scalar_gt[i8]
i8.__ge__ = scalar_ge[i8]

i16.__eq__ = scalar_eq[i16]
i16.__ne__ = scalar_ne[i16]
i16.__lt__ = scalar_lt[i16]
i16.__le__ = scalar_le[i16]
i16.__gt__ = scalar_gt[i16]
i16.__ge__ = scalar_ge[i16]

i32.__eq__ = scalar_eq[i32]
i32.__ne__ = scalar_ne[i32]
i32.__lt__ = scalar_lt[i32]
i32.__le__ = scalar_le[i32]
i32.__gt__ = scalar_gt[i32]
i32.__ge__ = scalar_ge[i32]

i64.__eq__ = scalar_eq[i64]
i64.__ne__ = scalar_ne[i64]
i64.__lt__ = scalar_lt[i64]
i64.__le__ = scalar_le[i64]
i64.__gt__ = scalar_gt[i64]
i64.__ge__ = scalar_ge[i64]

i128.__eq__ = scalar_eq[i128]
i128.__ne__ = scalar_ne[i128]
i128.__lt__ = scalar_lt[i128]
i128.__le__ = scalar_le[i128]
i128.__gt__ = scalar_gt[i128]
i128.__ge__ = scalar_ge[i128]

isize.__eq__ = scalar_eq[isize]
isize.__ne__ = scalar_ne[isize]
isize.__lt__ = scalar_lt[isize]
isize.__le__ = scalar_le[isize]
isize.__gt__ = scalar_gt[isize]
isize.__ge__ = scalar_ge[isize]

u8.__eq__ = scalar_eq[u8]
u8.__ne__ = scalar_ne[u8]
u8.__lt__ = scalar_lt[u8]
u8.__le__ = scalar_le[u8]
u8.__gt__ = scalar_gt[u8]
u8.__ge__ = scalar_ge[u8]

u16.__eq__ = scalar_eq[u16]
u16.__ne__ = scalar_ne[u16]
u16.__lt__ = scalar_lt[u16]
u16.__le__ = scalar_le[u16]
u16.__gt__ = scalar_gt[u16]
u16.__ge__ = scalar_ge[u16]

u32.__eq__ = scalar_eq[u32]
u32.__ne__ = scalar_ne[u32]
u32.__lt__ = scalar_lt[u32]
u32.__le__ = scalar_le[u32]
u32.__gt__ = scalar_gt[u32]
u32.__ge__ = scalar_ge[u32]

u64.__eq__ = scalar_eq[u64]
u64.__ne__ = scalar_ne[u64]
u64.__lt__ = scalar_lt[u64]
u64.__le__ = scalar_le[u64]
u64.__gt__ = scalar_gt[u64]
u64.__ge__ = scalar_ge[u64]

u128.__eq__ = scalar_eq[u128]
u128.__ne__ = scalar_ne[u128]
u128.__lt__ = scalar_lt[u128]
u128.__le__ = scalar_le[u128]
u128.__gt__ = scalar_gt[u128]
u128.__ge__ = scalar_ge[u128]

usize.__eq__ = scalar_eq[usize]
usize.__ne__ = scalar_ne[usize]
usize.__lt__ = scalar_lt[usize]
usize.__le__ = scalar_le[usize]
usize.__gt__ = scalar_gt[usize]
usize.__ge__ = scalar_ge[usize]

f32.__eq__ = scalar_eq[f32]
f32.__ne__ = scalar_ne[f32]
f32.__lt__ = scalar_lt[f32]
f32.__le__ = scalar_le[f32]
f32.__gt__ = scalar_gt[f32]
f32.__ge__ = scalar_ge[f32]

f64.__eq__ = scalar_eq[f64]
f64.__ne__ = scalar_ne[f64]
f64.__lt__ = scalar_lt[f64]
f64.__le__ = scalar_le[f64]
f64.__gt__ = scalar_gt[f64]
f64.__ge__ = scalar_ge[f64]

bool.__eq__ = scalar_eq[bool]
bool.__ne__ = scalar_ne[bool]
bool.__lt__ = scalar_lt[bool]
bool.__le__ = scalar_le[bool]
bool.__gt__ = scalar_gt[bool]
bool.__ge__ = scalar_ge[bool]

@fallible_arithmetic
@inline
def i_to_i[S,T]( value: S ) -> Result[T,OverflowError]:
	return compiler.checked_convert( T, value )

@inline
def i_to_i_identity[T]( value: T ) -> T:
	return value

# --- int-to-int value-preserving conversions ------------------------

i8.to_i8 = i_to_i_identity[i8]
i8.to_i16 = i_to_i[i8,i16]
i8.to_i32 = i_to_i[i8,i32]
i8.to_i64 = i_to_i[i8,i64]
i8.to_i128 = i_to_i[i8,i128]
i8.to_isize = i_to_i[i8,isize]
i8.to_u8 = i_to_i[i8,u8]
i8.to_u16 = i_to_i[i8,u16]
i8.to_u32 = i_to_i[i8,u32]
i8.to_u64 = i_to_i[i8,u64]
i8.to_u128 = i_to_i[i8,u128]
i8.to_usize = i_to_i[i8,usize]

i16.to_i8 = i_to_i[i16,i8]
i16.to_i16 = i_to_i_identity[i16]
i16.to_i32 = i_to_i[i16,i32]
i16.to_i64 = i_to_i[i16,i64]
i16.to_i128 = i_to_i[i16,i128]
i16.to_isize = i_to_i[i16,isize]
i16.to_u8 = i_to_i[i16,u8]
i16.to_u16 = i_to_i[i16,u16]
i16.to_u32 = i_to_i[i16,u32]
i16.to_u64 = i_to_i[i16,u64]
i16.to_u128 = i_to_i[i16,u128]
i16.to_usize = i_to_i[i16,usize]

i32.to_i8 = i_to_i[i32,i8]
i32.to_i16 = i_to_i[i32,i16]
i32.to_i32 = i_to_i_identity[i32]
i32.to_i64 = i_to_i[i32,i64]
i32.to_i128 = i_to_i[i32,i128]
i32.to_isize = i_to_i[i32,isize]
i32.to_u8 = i_to_i[i32,u8]
i32.to_u16 = i_to_i[i32,u16]
i32.to_u32 = i_to_i[i32,u32]
i32.to_u64 = i_to_i[i32,u64]
i32.to_u128 = i_to_i[i32,u128]
i32.to_usize = i_to_i[i32,usize]

i64.to_i8 = i_to_i[i64,i8]
i64.to_i16 = i_to_i[i64,i16]
i64.to_i32 = i_to_i[i64,i32]
i64.to_i64 = i_to_i_identity[i64]
i64.to_i128 = i_to_i[i64,i128]
i64.to_isize = i_to_i[i64,isize]
i64.to_u8 = i_to_i[i64,u8]
i64.to_u16 = i_to_i[i64,u16]
i64.to_u32 = i_to_i[i64,u32]
i64.to_u64 = i_to_i[i64,u64]
i64.to_u128 = i_to_i[i64,u128]
i64.to_usize = i_to_i[i64,usize]

i128.to_i8 = i_to_i[i128,i8]
i128.to_i16 = i_to_i[i128,i16]
i128.to_i32 = i_to_i[i128,i32]
i128.to_i64 = i_to_i[i128,i64]
i128.to_i128 = i_to_i_identity[i128]
i128.to_isize = i_to_i[i128,isize]
i128.to_u8 = i_to_i[i128,u8]
i128.to_u16 = i_to_i[i128,u16]
i128.to_u32 = i_to_i[i128,u32]
i128.to_u64 = i_to_i[i128,u64]
i128.to_u128 = i_to_i[i128,u128]
i128.to_usize = i_to_i[i128,usize]

isize.to_i8 = i_to_i[isize,i8]
isize.to_i16 = i_to_i[isize,i16]
isize.to_i32 = i_to_i[isize,i32]
isize.to_i64 = i_to_i[isize,i64]
isize.to_i128 = i_to_i[isize,i128]
isize.to_isize = i_to_i_identity[isize]
isize.to_u8 = i_to_i[isize,u8]
isize.to_u16 = i_to_i[isize,u16]
isize.to_u32 = i_to_i[isize,u32]
isize.to_u64 = i_to_i[isize,u64]
isize.to_u128 = i_to_i[isize,u128]
isize.to_usize = i_to_i[isize,usize]

u8.to_i8 = i_to_i[u8,i8]
u8.to_i16 = i_to_i[u8,i16]
u8.to_i32 = i_to_i[u8,i32]
u8.to_i64 = i_to_i[u8,i64]
u8.to_i128 = i_to_i[u8,i128]
u8.to_isize = i_to_i[u8,isize]
u8.to_u8 = i_to_i_identity[u8]
u8.to_u16 = i_to_i[u8,u16]
u8.to_u32 = i_to_i[u8,u32]
u8.to_u64 = i_to_i[u8,u64]
u8.to_u128 = i_to_i[u8,u128]
u8.to_usize = i_to_i[u8,usize]

u16.to_i8 = i_to_i[u16,i8]
u16.to_i16 = i_to_i[u16,i16]
u16.to_i32 = i_to_i[u16,i32]
u16.to_i64 = i_to_i[u16,i64]
u16.to_i128 = i_to_i[u16,i128]
u16.to_isize = i_to_i[u16,isize]
u16.to_u8 = i_to_i[u16,u8]
u16.to_u16 = i_to_i_identity[u16]
u16.to_u32 = i_to_i[u16,u32]
u16.to_u64 = i_to_i[u16,u64]
u16.to_u128 = i_to_i[u16,u128]
u16.to_usize = i_to_i[u16,usize]

u32.to_i8 = i_to_i[u32,i8]
u32.to_i16 = i_to_i[u32,i16]
u32.to_i32 = i_to_i[u32,i32]
u32.to_i64 = i_to_i[u32,i64]
u32.to_i128 = i_to_i[u32,i128]
u32.to_isize = i_to_i[u32,isize]
u32.to_u8 = i_to_i[u32,u8]
u32.to_u16 = i_to_i[u32,u16]
u32.to_u32 = i_to_i_identity[u32]
u32.to_u64 = i_to_i[u32,u64]
u32.to_u128 = i_to_i[u32,u128]
u32.to_usize = i_to_i[u32,usize]

u64.to_i8 = i_to_i[u64,i8]
u64.to_i16 = i_to_i[u64,i16]
u64.to_i32 = i_to_i[u64,i32]
u64.to_i64 = i_to_i[u64,i64]
u64.to_i128 = i_to_i[u64,i128]
u64.to_isize = i_to_i[u64,isize]
u64.to_u8 = i_to_i[u64,u8]
u64.to_u16 = i_to_i[u64,u16]
u64.to_u32 = i_to_i[u64,u32]
u64.to_u64 = i_to_i_identity[u64]
u64.to_u128 = i_to_i[u64,u128]
u64.to_usize = i_to_i[u64,usize]

u128.to_i8 = i_to_i[u128,i8]
u128.to_i16 = i_to_i[u128,i16]
u128.to_i32 = i_to_i[u128,i32]
u128.to_i64 = i_to_i[u128,i64]
u128.to_i128 = i_to_i[u128,i128]
u128.to_isize = i_to_i[u128,isize]
u128.to_u8 = i_to_i[u128,u8]
u128.to_u16 = i_to_i[u128,u16]
u128.to_u32 = i_to_i[u128,u32]
u128.to_u64 = i_to_i[u128,u64]
u128.to_u128 = i_to_i_identity[u128]
u128.to_usize = i_to_i[u128,usize]

usize.to_i8 = i_to_i[usize,i8]
usize.to_i16 = i_to_i[usize,i16]
usize.to_i32 = i_to_i[usize,i32]
usize.to_i64 = i_to_i[usize,i64]
usize.to_i128 = i_to_i[usize,i128]
usize.to_isize = i_to_i[usize,isize]
usize.to_u8 = i_to_i[usize,u8]
usize.to_u16 = i_to_i[usize,u16]
usize.to_u32 = i_to_i[usize,u32]
usize.to_u64 = i_to_i[usize,u64]
usize.to_u128 = i_to_i[usize,u128]
usize.to_usize = i_to_i_identity[usize]

_INT_DECIMAL_DIGIT_CHARS: str = '0123456789'

def i_str_unsigned[T]( value: T ) -> str:
	if value == 0:
		return '0'
	digits: list[str] = list[str]() # least-significant digit first
	with compiler.panic_arithmetic( 'dividing/moduloing a non-negative value by the literal 10 never zero-divides or overflows' ):
		v: T = value
		while v != 0:
			digit: T = v % 10
			digit_index: usize = usize( digit )
			digit_index_end: usize = digit_index + 1
			digits.append( _INT_DECIMAL_DIGIT_CHARS._byte_slice( digit_index, digit_index_end )).unwrap( 'i_str_unsigned: append failed' )
			v = v // 10
	count: usize = digits.__len__()
	ordered: list[str] = list[str]() # most-significant digit first
	i: usize = count
	with compiler.panic_arithmetic( 'bounded by count, cannot underflow' ):
		while i > 0:
			i -= 1
			ordered.append( digits.__getitem__( i ).unwrap( 'i_str_unsigned: index in bounds by construction' )).unwrap( 'i_str_unsigned: append failed' )
	return ''.join( ordered )

def i_str_signed[T]( value: T ) -> str:
	if value == 0:
		return '0'
	is_negative: bool = value < 0
	digits: list[str] = list[str]() # least-significant digit first
	with compiler.panic_arithmetic( 'dividing/moduloing by the literal 10 never zero-divides; the divisor is never -1, so the signed MIN/-1 overflow case never applies here' ):
		v: T = value
		while v != 0:
			digit: T = v % 10 # C-truncating: same sign as v (or zero), never MIN-magnitude
			magnitude_digit: T = -digit if digit < 0 else digit # a single digit (0-9) - safe to negate for any width, unlike v itself
			digit_index: usize = usize( magnitude_digit )
			digit_index_end: usize = digit_index + 1
			digits.append( _INT_DECIMAL_DIGIT_CHARS._byte_slice( digit_index, digit_index_end )).unwrap( 'i_str_signed: append failed' )
			v = v // 10
	count: usize = digits.__len__()
	ordered: list[str] = list[str]() # most-significant digit first
	i: usize = count
	with compiler.panic_arithmetic( 'bounded by count, cannot underflow' ):
		while i > 0:
			i -= 1
			ordered.append( digits.__getitem__( i ).unwrap( 'i_str_signed: index in bounds by construction' )).unwrap( 'i_str_signed: append failed' )
	joined: str = ''.join( ordered )
	if is_negative:
		return '-' + joined
	return joined

# --- __str__/__repr__ -------------------------------------------------

i8.__str__ = i_str_signed[i8]
i8.__repr__ = i_str_signed[i8]
i16.__str__ = i_str_signed[i16]
i16.__repr__ = i_str_signed[i16]
i32.__str__ = i_str_signed[i32]
i32.__repr__ = i_str_signed[i32]
i64.__str__ = i_str_signed[i64]
i64.__repr__ = i_str_signed[i64]
i128.__str__ = i_str_signed[i128]
i128.__repr__ = i_str_signed[i128]
isize.__str__ = i_str_signed[isize]
isize.__repr__ = i_str_signed[isize]

u8.__str__ = i_str_unsigned[u8]
u8.__repr__ = i_str_unsigned[u8]
u16.__str__ = i_str_unsigned[u16]
u16.__repr__ = i_str_unsigned[u16]
u32.__str__ = i_str_unsigned[u32]
u32.__repr__ = i_str_unsigned[u32]
u64.__str__ = i_str_unsigned[u64]
u64.__repr__ = i_str_unsigned[u64]
u128.__str__ = i_str_unsigned[u128]
u128.__repr__ = i_str_unsigned[u128]
usize.__str__ = i_str_unsigned[usize]
usize.__repr__ = i_str_unsigned[usize]
