# GENERATED by gen_scalar_arith.py - do not hand-edit; re-run the
# generator instead. One real generic function body per (operator,
# mode) pair (see that script's own header comment), specialized per
# concrete scalar type via one registration line each below.

@fallible_arithmetic
@inline
def i_add_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_add( value, other )

@inline
def i_add_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_add( value, other )

@inline
def i_add_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_add( value, other )

@fallible_arithmetic
@inline
def i_sub_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_sub( value, other )

@inline
def i_sub_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_sub( value, other )

@inline
def i_sub_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_sub( value, other )

@fallible_arithmetic
@inline
def i_mul_checked[T]( value: T, other: T ) -> Result[T,OverflowError]:
	return compiler.checked_mul( value, other )

@inline
def i_mul_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_mul( value, other )

@inline
def i_mul_saturated[T]( value: T, other: T ) -> T:
	return compiler.saturated_mul( value, other )

@fallible_arithmetic
@inline
def i_floordiv_checked_signed[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|OverflowError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@inline
def i_floordiv_checked_unsigned[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.checked_floordiv( value, other )

@fallible_arithmetic
@inline
def i_floordiv_wrapped[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.wrapped_floordiv( value, other )

@fallible_arithmetic
@inline
def i_floordiv_saturated[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.saturated_floordiv( value, other )

@fallible_arithmetic
@inline
def i_mod_checked_signed[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|OverflowError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@inline
def i_mod_checked_unsigned[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.checked_mod( value, other )

@fallible_arithmetic
@inline
def i_mod_wrapped[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.wrapped_mod( value, other )

@fallible_arithmetic
@inline
def i_mod_saturated[T]( value: T, other: T ) -> Result[T,ZeroDivisionError]:
	return compiler.saturated_mod( value, other )

@fallible_arithmetic
@inline
def f_add_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:
	return compiler.checked_add( value, other )

@inline
def f_add_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_add( value, other )

@inline
def f_add_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_add( value, other )

@fallible_arithmetic
@inline
def f_sub_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:
	return compiler.checked_sub( value, other )

@inline
def f_sub_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_sub( value, other )

@inline
def f_sub_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_sub( value, other )

@fallible_arithmetic
@inline
def f_mul_checked[T]( value: T, other: T ) -> Result[T,FloatingPointError]:
	return compiler.checked_mul( value, other )

@inline
def f_mul_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_mul( value, other )

@inline
def f_mul_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_mul( value, other )

@fallible_arithmetic
@inline
def f_truediv_checked[T]( value: T, other: T ) -> Result[T,ZeroDivisionError|FloatingPointError]:
	return compiler.checked_truediv( value, other )

@inline
def f_truediv_wrapped[T]( value: T, other: T ) -> T:
	return compiler.wrapped_truediv( value, other )

@inline
def f_truediv_saturated[T]( value: T, other: T ) -> T:
	return compiler.wrapped_truediv( value, other )

# --- int add/sub/mul -----------------------------------------------

i8.__add__ = i_add_checked[i8]
i8.__wrapped_add__ = i_add_wrapped[i8]
i8.__saturated_add__ = i_add_saturated[i8]
i8.__sub__ = i_sub_checked[i8]
i8.__wrapped_sub__ = i_sub_wrapped[i8]
i8.__saturated_sub__ = i_sub_saturated[i8]
i8.__mul__ = i_mul_checked[i8]
i8.__wrapped_mul__ = i_mul_wrapped[i8]
i8.__saturated_mul__ = i_mul_saturated[i8]

i16.__add__ = i_add_checked[i16]
i16.__wrapped_add__ = i_add_wrapped[i16]
i16.__saturated_add__ = i_add_saturated[i16]
i16.__sub__ = i_sub_checked[i16]
i16.__wrapped_sub__ = i_sub_wrapped[i16]
i16.__saturated_sub__ = i_sub_saturated[i16]
i16.__mul__ = i_mul_checked[i16]
i16.__wrapped_mul__ = i_mul_wrapped[i16]
i16.__saturated_mul__ = i_mul_saturated[i16]

i32.__add__ = i_add_checked[i32]
i32.__wrapped_add__ = i_add_wrapped[i32]
i32.__saturated_add__ = i_add_saturated[i32]
i32.__sub__ = i_sub_checked[i32]
i32.__wrapped_sub__ = i_sub_wrapped[i32]
i32.__saturated_sub__ = i_sub_saturated[i32]
i32.__mul__ = i_mul_checked[i32]
i32.__wrapped_mul__ = i_mul_wrapped[i32]
i32.__saturated_mul__ = i_mul_saturated[i32]

i64.__add__ = i_add_checked[i64]
i64.__wrapped_add__ = i_add_wrapped[i64]
i64.__saturated_add__ = i_add_saturated[i64]
i64.__sub__ = i_sub_checked[i64]
i64.__wrapped_sub__ = i_sub_wrapped[i64]
i64.__saturated_sub__ = i_sub_saturated[i64]
i64.__mul__ = i_mul_checked[i64]
i64.__wrapped_mul__ = i_mul_wrapped[i64]
i64.__saturated_mul__ = i_mul_saturated[i64]

i128.__add__ = i_add_checked[i128]
i128.__wrapped_add__ = i_add_wrapped[i128]
i128.__saturated_add__ = i_add_saturated[i128]
i128.__sub__ = i_sub_checked[i128]
i128.__wrapped_sub__ = i_sub_wrapped[i128]
i128.__saturated_sub__ = i_sub_saturated[i128]
i128.__mul__ = i_mul_checked[i128]
i128.__wrapped_mul__ = i_mul_wrapped[i128]
i128.__saturated_mul__ = i_mul_saturated[i128]

isize.__add__ = i_add_checked[isize]
isize.__wrapped_add__ = i_add_wrapped[isize]
isize.__saturated_add__ = i_add_saturated[isize]
isize.__sub__ = i_sub_checked[isize]
isize.__wrapped_sub__ = i_sub_wrapped[isize]
isize.__saturated_sub__ = i_sub_saturated[isize]
isize.__mul__ = i_mul_checked[isize]
isize.__wrapped_mul__ = i_mul_wrapped[isize]
isize.__saturated_mul__ = i_mul_saturated[isize]

u8.__add__ = i_add_checked[u8]
u8.__wrapped_add__ = i_add_wrapped[u8]
u8.__saturated_add__ = i_add_saturated[u8]
u8.__sub__ = i_sub_checked[u8]
u8.__wrapped_sub__ = i_sub_wrapped[u8]
u8.__saturated_sub__ = i_sub_saturated[u8]
u8.__mul__ = i_mul_checked[u8]
u8.__wrapped_mul__ = i_mul_wrapped[u8]
u8.__saturated_mul__ = i_mul_saturated[u8]

u16.__add__ = i_add_checked[u16]
u16.__wrapped_add__ = i_add_wrapped[u16]
u16.__saturated_add__ = i_add_saturated[u16]
u16.__sub__ = i_sub_checked[u16]
u16.__wrapped_sub__ = i_sub_wrapped[u16]
u16.__saturated_sub__ = i_sub_saturated[u16]
u16.__mul__ = i_mul_checked[u16]
u16.__wrapped_mul__ = i_mul_wrapped[u16]
u16.__saturated_mul__ = i_mul_saturated[u16]

u32.__add__ = i_add_checked[u32]
u32.__wrapped_add__ = i_add_wrapped[u32]
u32.__saturated_add__ = i_add_saturated[u32]
u32.__sub__ = i_sub_checked[u32]
u32.__wrapped_sub__ = i_sub_wrapped[u32]
u32.__saturated_sub__ = i_sub_saturated[u32]
u32.__mul__ = i_mul_checked[u32]
u32.__wrapped_mul__ = i_mul_wrapped[u32]
u32.__saturated_mul__ = i_mul_saturated[u32]

u64.__add__ = i_add_checked[u64]
u64.__wrapped_add__ = i_add_wrapped[u64]
u64.__saturated_add__ = i_add_saturated[u64]
u64.__sub__ = i_sub_checked[u64]
u64.__wrapped_sub__ = i_sub_wrapped[u64]
u64.__saturated_sub__ = i_sub_saturated[u64]
u64.__mul__ = i_mul_checked[u64]
u64.__wrapped_mul__ = i_mul_wrapped[u64]
u64.__saturated_mul__ = i_mul_saturated[u64]

u128.__add__ = i_add_checked[u128]
u128.__wrapped_add__ = i_add_wrapped[u128]
u128.__saturated_add__ = i_add_saturated[u128]
u128.__sub__ = i_sub_checked[u128]
u128.__wrapped_sub__ = i_sub_wrapped[u128]
u128.__saturated_sub__ = i_sub_saturated[u128]
u128.__mul__ = i_mul_checked[u128]
u128.__wrapped_mul__ = i_mul_wrapped[u128]
u128.__saturated_mul__ = i_mul_saturated[u128]

usize.__add__ = i_add_checked[usize]
usize.__wrapped_add__ = i_add_wrapped[usize]
usize.__saturated_add__ = i_add_saturated[usize]
usize.__sub__ = i_sub_checked[usize]
usize.__wrapped_sub__ = i_sub_wrapped[usize]
usize.__saturated_sub__ = i_sub_saturated[usize]
usize.__mul__ = i_mul_checked[usize]
usize.__wrapped_mul__ = i_mul_wrapped[usize]
usize.__saturated_mul__ = i_mul_saturated[usize]

# --- int floordiv/mod -----------------------------------------------

i8.__floordiv__ = i_floordiv_checked_signed[i8]
i8.__wrapped_floordiv__ = i_floordiv_wrapped[i8]
i8.__saturated_floordiv__ = i_floordiv_saturated[i8]
i8.__mod__ = i_mod_checked_signed[i8]
i8.__wrapped_mod__ = i_mod_wrapped[i8]
i8.__saturated_mod__ = i_mod_saturated[i8]

i16.__floordiv__ = i_floordiv_checked_signed[i16]
i16.__wrapped_floordiv__ = i_floordiv_wrapped[i16]
i16.__saturated_floordiv__ = i_floordiv_saturated[i16]
i16.__mod__ = i_mod_checked_signed[i16]
i16.__wrapped_mod__ = i_mod_wrapped[i16]
i16.__saturated_mod__ = i_mod_saturated[i16]

i32.__floordiv__ = i_floordiv_checked_signed[i32]
i32.__wrapped_floordiv__ = i_floordiv_wrapped[i32]
i32.__saturated_floordiv__ = i_floordiv_saturated[i32]
i32.__mod__ = i_mod_checked_signed[i32]
i32.__wrapped_mod__ = i_mod_wrapped[i32]
i32.__saturated_mod__ = i_mod_saturated[i32]

i64.__floordiv__ = i_floordiv_checked_signed[i64]
i64.__wrapped_floordiv__ = i_floordiv_wrapped[i64]
i64.__saturated_floordiv__ = i_floordiv_saturated[i64]
i64.__mod__ = i_mod_checked_signed[i64]
i64.__wrapped_mod__ = i_mod_wrapped[i64]
i64.__saturated_mod__ = i_mod_saturated[i64]

i128.__floordiv__ = i_floordiv_checked_signed[i128]
i128.__wrapped_floordiv__ = i_floordiv_wrapped[i128]
i128.__saturated_floordiv__ = i_floordiv_saturated[i128]
i128.__mod__ = i_mod_checked_signed[i128]
i128.__wrapped_mod__ = i_mod_wrapped[i128]
i128.__saturated_mod__ = i_mod_saturated[i128]

isize.__floordiv__ = i_floordiv_checked_signed[isize]
isize.__wrapped_floordiv__ = i_floordiv_wrapped[isize]
isize.__saturated_floordiv__ = i_floordiv_saturated[isize]
isize.__mod__ = i_mod_checked_signed[isize]
isize.__wrapped_mod__ = i_mod_wrapped[isize]
isize.__saturated_mod__ = i_mod_saturated[isize]

u8.__floordiv__ = i_floordiv_checked_unsigned[u8]
u8.__wrapped_floordiv__ = i_floordiv_wrapped[u8]
u8.__saturated_floordiv__ = i_floordiv_saturated[u8]
u8.__mod__ = i_mod_checked_unsigned[u8]
u8.__wrapped_mod__ = i_mod_wrapped[u8]
u8.__saturated_mod__ = i_mod_saturated[u8]

u16.__floordiv__ = i_floordiv_checked_unsigned[u16]
u16.__wrapped_floordiv__ = i_floordiv_wrapped[u16]
u16.__saturated_floordiv__ = i_floordiv_saturated[u16]
u16.__mod__ = i_mod_checked_unsigned[u16]
u16.__wrapped_mod__ = i_mod_wrapped[u16]
u16.__saturated_mod__ = i_mod_saturated[u16]

u32.__floordiv__ = i_floordiv_checked_unsigned[u32]
u32.__wrapped_floordiv__ = i_floordiv_wrapped[u32]
u32.__saturated_floordiv__ = i_floordiv_saturated[u32]
u32.__mod__ = i_mod_checked_unsigned[u32]
u32.__wrapped_mod__ = i_mod_wrapped[u32]
u32.__saturated_mod__ = i_mod_saturated[u32]

u64.__floordiv__ = i_floordiv_checked_unsigned[u64]
u64.__wrapped_floordiv__ = i_floordiv_wrapped[u64]
u64.__saturated_floordiv__ = i_floordiv_saturated[u64]
u64.__mod__ = i_mod_checked_unsigned[u64]
u64.__wrapped_mod__ = i_mod_wrapped[u64]
u64.__saturated_mod__ = i_mod_saturated[u64]

u128.__floordiv__ = i_floordiv_checked_unsigned[u128]
u128.__wrapped_floordiv__ = i_floordiv_wrapped[u128]
u128.__saturated_floordiv__ = i_floordiv_saturated[u128]
u128.__mod__ = i_mod_checked_unsigned[u128]
u128.__wrapped_mod__ = i_mod_wrapped[u128]
u128.__saturated_mod__ = i_mod_saturated[u128]

usize.__floordiv__ = i_floordiv_checked_unsigned[usize]
usize.__wrapped_floordiv__ = i_floordiv_wrapped[usize]
usize.__saturated_floordiv__ = i_floordiv_saturated[usize]
usize.__mod__ = i_mod_checked_unsigned[usize]
usize.__wrapped_mod__ = i_mod_wrapped[usize]
usize.__saturated_mod__ = i_mod_saturated[usize]

# --- float add/sub/mul ----------------------------------------------

f32.__add__ = f_add_checked[f32]
f32.__wrapped_add__ = f_add_wrapped[f32]
f32.__saturated_add__ = f_add_saturated[f32]
f32.__sub__ = f_sub_checked[f32]
f32.__wrapped_sub__ = f_sub_wrapped[f32]
f32.__saturated_sub__ = f_sub_saturated[f32]
f32.__mul__ = f_mul_checked[f32]
f32.__wrapped_mul__ = f_mul_wrapped[f32]
f32.__saturated_mul__ = f_mul_saturated[f32]

f64.__add__ = f_add_checked[f64]
f64.__wrapped_add__ = f_add_wrapped[f64]
f64.__saturated_add__ = f_add_saturated[f64]
f64.__sub__ = f_sub_checked[f64]
f64.__wrapped_sub__ = f_sub_wrapped[f64]
f64.__saturated_sub__ = f_sub_saturated[f64]
f64.__mul__ = f_mul_checked[f64]
f64.__wrapped_mul__ = f_mul_wrapped[f64]
f64.__saturated_mul__ = f_mul_saturated[f64]

# --- float truediv ---------------------------------------------------

f32.__truediv__ = f_truediv_checked[f32]
f32.__wrapped_truediv__ = f_truediv_wrapped[f32]
f32.__saturated_truediv__ = f_truediv_saturated[f32]
f64.__truediv__ = f_truediv_checked[f64]
f64.__wrapped_truediv__ = f_truediv_wrapped[f64]
f64.__saturated_truediv__ = f_truediv_saturated[f64]

@fallible_arithmetic
@inline
def i_to_i[S,T]( value: S ) -> Result[T,OverflowError]:
	return compiler.checked_convert( T, value )

@inline
def i_to_i_identity[T]( value: T ) -> T:
	return value

# --- int-to-int value-preserving conversions ------------------------

i8.to_i8 = i_to_i_identity[i8]
i8.to_i16 = i_to_i[i8,i16]
i8.to_i32 = i_to_i[i8,i32]
i8.to_i64 = i_to_i[i8,i64]
i8.to_i128 = i_to_i[i8,i128]
i8.to_isize = i_to_i[i8,isize]
i8.to_u8 = i_to_i[i8,u8]
i8.to_u16 = i_to_i[i8,u16]
i8.to_u32 = i_to_i[i8,u32]
i8.to_u64 = i_to_i[i8,u64]
i8.to_u128 = i_to_i[i8,u128]
i8.to_usize = i_to_i[i8,usize]

i16.to_i8 = i_to_i[i16,i8]
i16.to_i16 = i_to_i_identity[i16]
i16.to_i32 = i_to_i[i16,i32]
i16.to_i64 = i_to_i[i16,i64]
i16.to_i128 = i_to_i[i16,i128]
i16.to_isize = i_to_i[i16,isize]
i16.to_u8 = i_to_i[i16,u8]
i16.to_u16 = i_to_i[i16,u16]
i16.to_u32 = i_to_i[i16,u32]
i16.to_u64 = i_to_i[i16,u64]
i16.to_u128 = i_to_i[i16,u128]
i16.to_usize = i_to_i[i16,usize]

i32.to_i8 = i_to_i[i32,i8]
i32.to_i16 = i_to_i[i32,i16]
i32.to_i32 = i_to_i_identity[i32]
i32.to_i64 = i_to_i[i32,i64]
i32.to_i128 = i_to_i[i32,i128]
i32.to_isize = i_to_i[i32,isize]
i32.to_u8 = i_to_i[i32,u8]
i32.to_u16 = i_to_i[i32,u16]
i32.to_u32 = i_to_i[i32,u32]
i32.to_u64 = i_to_i[i32,u64]
i32.to_u128 = i_to_i[i32,u128]
i32.to_usize = i_to_i[i32,usize]

i64.to_i8 = i_to_i[i64,i8]
i64.to_i16 = i_to_i[i64,i16]
i64.to_i32 = i_to_i[i64,i32]
i64.to_i64 = i_to_i_identity[i64]
i64.to_i128 = i_to_i[i64,i128]
i64.to_isize = i_to_i[i64,isize]
i64.to_u8 = i_to_i[i64,u8]
i64.to_u16 = i_to_i[i64,u16]
i64.to_u32 = i_to_i[i64,u32]
i64.to_u64 = i_to_i[i64,u64]
i64.to_u128 = i_to_i[i64,u128]
i64.to_usize = i_to_i[i64,usize]

i128.to_i8 = i_to_i[i128,i8]
i128.to_i16 = i_to_i[i128,i16]
i128.to_i32 = i_to_i[i128,i32]
i128.to_i64 = i_to_i[i128,i64]
i128.to_i128 = i_to_i_identity[i128]
i128.to_isize = i_to_i[i128,isize]
i128.to_u8 = i_to_i[i128,u8]
i128.to_u16 = i_to_i[i128,u16]
i128.to_u32 = i_to_i[i128,u32]
i128.to_u64 = i_to_i[i128,u64]
i128.to_u128 = i_to_i[i128,u128]
i128.to_usize = i_to_i[i128,usize]

isize.to_i8 = i_to_i[isize,i8]
isize.to_i16 = i_to_i[isize,i16]
isize.to_i32 = i_to_i[isize,i32]
isize.to_i64 = i_to_i[isize,i64]
isize.to_i128 = i_to_i[isize,i128]
isize.to_isize = i_to_i_identity[isize]
isize.to_u8 = i_to_i[isize,u8]
isize.to_u16 = i_to_i[isize,u16]
isize.to_u32 = i_to_i[isize,u32]
isize.to_u64 = i_to_i[isize,u64]
isize.to_u128 = i_to_i[isize,u128]
isize.to_usize = i_to_i[isize,usize]

u8.to_i8 = i_to_i[u8,i8]
u8.to_i16 = i_to_i[u8,i16]
u8.to_i32 = i_to_i[u8,i32]
u8.to_i64 = i_to_i[u8,i64]
u8.to_i128 = i_to_i[u8,i128]
u8.to_isize = i_to_i[u8,isize]
u8.to_u8 = i_to_i_identity[u8]
u8.to_u16 = i_to_i[u8,u16]
u8.to_u32 = i_to_i[u8,u32]
u8.to_u64 = i_to_i[u8,u64]
u8.to_u128 = i_to_i[u8,u128]
u8.to_usize = i_to_i[u8,usize]

u16.to_i8 = i_to_i[u16,i8]
u16.to_i16 = i_to_i[u16,i16]
u16.to_i32 = i_to_i[u16,i32]
u16.to_i64 = i_to_i[u16,i64]
u16.to_i128 = i_to_i[u16,i128]
u16.to_isize = i_to_i[u16,isize]
u16.to_u8 = i_to_i[u16,u8]
u16.to_u16 = i_to_i_identity[u16]
u16.to_u32 = i_to_i[u16,u32]
u16.to_u64 = i_to_i[u16,u64]
u16.to_u128 = i_to_i[u16,u128]
u16.to_usize = i_to_i[u16,usize]

u32.to_i8 = i_to_i[u32,i8]
u32.to_i16 = i_to_i[u32,i16]
u32.to_i32 = i_to_i[u32,i32]
u32.to_i64 = i_to_i[u32,i64]
u32.to_i128 = i_to_i[u32,i128]
u32.to_isize = i_to_i[u32,isize]
u32.to_u8 = i_to_i[u32,u8]
u32.to_u16 = i_to_i[u32,u16]
u32.to_u32 = i_to_i_identity[u32]
u32.to_u64 = i_to_i[u32,u64]
u32.to_u128 = i_to_i[u32,u128]
u32.to_usize = i_to_i[u32,usize]

u64.to_i8 = i_to_i[u64,i8]
u64.to_i16 = i_to_i[u64,i16]
u64.to_i32 = i_to_i[u64,i32]
u64.to_i64 = i_to_i[u64,i64]
u64.to_i128 = i_to_i[u64,i128]
u64.to_isize = i_to_i[u64,isize]
u64.to_u8 = i_to_i[u64,u8]
u64.to_u16 = i_to_i[u64,u16]
u64.to_u32 = i_to_i[u64,u32]
u64.to_u64 = i_to_i_identity[u64]
u64.to_u128 = i_to_i[u64,u128]
u64.to_usize = i_to_i[u64,usize]

u128.to_i8 = i_to_i[u128,i8]
u128.to_i16 = i_to_i[u128,i16]
u128.to_i32 = i_to_i[u128,i32]
u128.to_i64 = i_to_i[u128,i64]
u128.to_i128 = i_to_i[u128,i128]
u128.to_isize = i_to_i[u128,isize]
u128.to_u8 = i_to_i[u128,u8]
u128.to_u16 = i_to_i[u128,u16]
u128.to_u32 = i_to_i[u128,u32]
u128.to_u64 = i_to_i[u128,u64]
u128.to_u128 = i_to_i_identity[u128]
u128.to_usize = i_to_i[u128,usize]

usize.to_i8 = i_to_i[usize,i8]
usize.to_i16 = i_to_i[usize,i16]
usize.to_i32 = i_to_i[usize,i32]
usize.to_i64 = i_to_i[usize,i64]
usize.to_i128 = i_to_i[usize,i128]
usize.to_isize = i_to_i[usize,isize]
usize.to_u8 = i_to_i[usize,u8]
usize.to_u16 = i_to_i[usize,u16]
usize.to_u32 = i_to_i[usize,u32]
usize.to_u64 = i_to_i[usize,u64]
usize.to_u128 = i_to_i[usize,u128]
usize.to_usize = i_to_i_identity[usize]
